import test from 'node:test';import assert from 'node:assert/strict';
import {archivedCandidates,evidenceCatalog} from '../lib/archived-profile-evidence.mjs';
import {database} from './search-sqlite-fixture.mjs';
import {syncPlayerIdentities} from '../scripts/sync-player-identities.mjs';
import {unresolvedSources,applyArchiveEvidence} from '../scripts/repair-archived-player-profiles.mjs';
const guid='12345678-1234-1234-1234-123456789abc';
test('TE neutral federation affiliation matches native nationality only within TE and preserves ambiguity',()=>{
 for(const [affiliation,nation]of [['RTF','RUS'],['BTF','BLR']]){
  const catalog=evidenceCatalog();catalog.add([{circuit:'tennis-europe',name:'Example Player',officialId:guid,nationality:nation}]);
  const row={circuit:'tennis-europe',display_name:'Example Player',official_id:'',nationality:affiliation,payload:'{}'};
  const e=catalog.resolve(row);assert.equal(e.officialId,guid);assert.equal(e.nationality,undefined);assert.equal(row.nationality,affiliation);
  assert.equal(catalog.resolve({...row,nationality:'KAZ'}),null);
  catalog.add([{circuit:'tennis-europe',name:'Example Player',officialId:'22345678-1234-1234-1234-123456789abc',nationality:nation}]);assert.equal(catalog.resolve(row),null);
  const itf=evidenceCatalog();itf.add([{circuit:'itf',name:'Example Player',officialId:'800123456',nationality:nation}]);assert.equal(itf.resolve({...row,circuit:'itf'}),null);
 }
});
test('retained document native ID/country and relative profile recover ID-only ITF',()=>{const catalog=evidenceCatalog();catalog.add(archivedCandidates('itf',{matches:[{teams:[{players:[{id:'800543439',name:'Aruzhan Nuranbay',nationalityCode:'KAZ',profileLink:'/en/players/aruzhan-nuranbay/800543439/kaz/jt/s/overview/'}]}]}]}));const e=catalog.resolve({circuit:'itf',official_id:'800543439',display_name:'Aruzhan Nuranbay',payload:'{}'});assert.match(e.profileUrl,/\/kaz\//);assert.equal(e.officialId,'800543439');});
test('retained full name order and equivalent nation codes resolve TE, conflicting GUIDs do not',()=>{const catalog=evidenceCatalog();catalog.add(archivedCandidates('tennis-europe',[{name:'SLANICEANU Sarah Ioana',participantId:guid,countryCode:'ROU'}]));const row={circuit:'tennis-europe',official_id:'',display_name:'Sarah Ioana SLANICEANU',nationality:'ROM',payload:'{}'};assert.equal(catalog.resolve(row).officialId,guid);catalog.add(archivedCandidates('tennis-europe',[{name:row.display_name,participantId:'22345678-1234-1234-1234-123456789abc',countryCode:'ROU'}]));assert.equal(catalog.resolve(row),null);});
test('tournament UUID never becomes a player profile and metadata conflicts remain unresolved',()=>{assert.equal(archivedCandidates('tennis-europe',{playerName:'Test Player',participantId:guid,profileUrl:'/sport/player.aspx?id='+guid+'&player=42'}).length,0);const catalog=evidenceCatalog();catalog.add(archivedCandidates('itf',{id:'800543439',name:'Corrected Name',nationalityCode:'KAZ',birthYear:2010}));assert.equal(catalog.resolve({circuit:'itf',official_id:'800543439',display_name:'Original Name',nationality:'ITA',payload:'{}'}),null);assert.equal(catalog.resolve({circuit:'itf',official_id:'800543439',display_name:'Original Name',payload:'{"birthYear":2011}'}),null);assert.match(catalog.resolve({circuit:'itf',official_id:'800543439',display_name:'Original Name',payload:'{}'}).profileUrl,/800543439/);});
test('D1_TEST_INITIAL_IMPORT D1_TEST_IDENTICAL_ZERO_WRITES D1_TEST_REAL_DELTAS_ONLY D1_TEST_INCOMPLETE_SOURCE_GUARD: verified source repair retains keys and replay has zero writes',async()=>{const d=database({identityMapping:true});try{d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['source','itf','800543439','ARUZHAN NURANBAY','Aruzhan Nuranbay','{}']);await syncPlayerIdentities(d.query);const catalog=evidenceCatalog();catalog.add(archivedCandidates('itf',{id:'800543439',name:'Aruzhan Nuranbay',nationalityCode:'KAZ'}));const rows=await unresolvedSources(d.query);assert.equal((await applyArchiveEvidence(d.query,rows,catalog)).repaired,1);await syncPlayerIdentities(d.query);assert.match((await d.query("SELECT profile_url FROM player_circuit_identities WHERE source_key='source'"))[0].profile_url,/\/kaz\//);const n=d.writes();assert.equal((await applyArchiveEvidence(d.query,await unresolvedSources(d.query),catalog)).repaired,0);assert.equal(d.writes(),n);await assert.rejects(()=>applyArchiveEvidence(d.query,[{...rows[0],payload:'broken'}],catalog));assert.equal(d.writes(),n);}finally{d.close();}});
test('concurrent source changes are retained and are never falsely counted as repaired',async()=>{const d=database({identityMapping:true});try{d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['source','itf','800543439','ARUZHAN NURANBAY','Aruzhan Nuranbay','{}']);await syncPlayerIdentities(d.query);const rows=await unresolvedSources(d.query),catalog=evidenceCatalog();catalog.add(archivedCandidates('itf',{id:'800543439',name:'Aruzhan Nuranbay',nationalityCode:'KAZ'}));d.execute("UPDATE search_acquired_players SET payload='{\"club\":\"Concurrent\"}' WHERE source_key='source'");const result=await applyArchiveEvidence(d.query,rows,catalog);assert.equal(result.repaired,0);assert.equal(result.records[0].status,'concurrent_change');assert.equal(JSON.parse((await d.query("SELECT payload FROM search_acquired_players WHERE source_key='source'"))[0].payload).club,'Concurrent');}finally{d.close();}});
