import test from 'node:test';import assert from 'node:assert/strict';
import {paginatedPlayerSearch} from '../lib/paginated-player-search.mjs';import {database} from './search-sqlite-fixture.mjs';
test('pages reach all 137 identities without truncation or duplicate cursors',async()=>{const d=database();try{for(let i=0;i<137;i++){const name='Test '+String(i).padStart(3,'0');d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['s'+i,'itf','','TEST '+String(i).padStart(3,'0'),name,'{}'])}let cursor='',names=[],pages=0;do{const page=await paginatedPlayerSearch(d.db,'Test',null,cursor);assert.ok(page.results.length<=60);names.push(...page.results.map(r=>r.name));cursor=page.nextCursor;pages++;assert.ok(pages<5)}while(cursor);assert.equal(names.length,137);assert.equal(new Set(names).size,137);assert.equal(pages,3);await assert.rejects(paginatedPlayerSearch(d.db,'Test',null,'bad'),/invalid_search_cursor/)}finally{d.close()}});
test('mixed source pages retain homonyms and prefer observed row for matching official identity',async()=>{const d=database();try{d.execute('INSERT INTO observed_players(source_key,circuit,official_id,normalized_name,display_name,payload) VALUES(?,?,?,?,?,?)',['o','itf','800671267','TEST PERSON','Test Person','{"nationality":"ITA"}']);d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['same','itf','800671267','TEST PERSON','Test Person','{}']);d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['other','itf','800671268','TEST PERSON','Test Person','{"nationality":"SUI"}']);const p=await paginatedPlayerSearch(d.db,'Person Test',null);assert.equal(p.results.length,2);assert.deepEqual(new Set(p.results.map(r=>r.nationality)),new Set(['ITA','SUI']))}finally{d.close()}});
test('one Darko Sartori result includes FITP and Europe; conflicting birth years remain separate',async()=>{const d=database();try{
 for(const [key,circuit,name,year]of [['f','fitp','DARKO SARTORI',2010],['e','tennis-europe','SARTORI DARKO',2010]])d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',[key,circuit,key,name,name,JSON.stringify({birthYear:year,nationality:'ITA'})]);
 let p=await paginatedPlayerSearch(d.db,'Darko Sartori',null);assert.equal(p.results.length,1);assert.deepEqual(new Set(p.results[0].sources),new Set(['fitp','tennis-europe']));
 d.execute("UPDATE search_acquired_players SET payload=? WHERE source_key='e'",['{"birthYear":2001,"nationality":"ITA"}']);p=await paginatedPlayerSearch(d.db,'Darko',null);assert.equal(p.results.length,2);
}finally{d.close()}});
test('reversed-name alias across page boundary is emitted only once and keeps both circuits',async()=>{const d=database();try{
 for(let i=0;i<65;i++)d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['t'+i,'itf','t'+i,'TEST '+String(i).padStart(3,'0'),'Test '+i,'{}']);
 for(const [key,circuit,name]of [['f','fitp','ALPHA TEST'],['e','tennis-europe','TEST ALPHA']])d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',[key,circuit,key,name,name,'{}']);
 let after='',found=[];do{const p=await paginatedPlayerSearch(d.db,'Test',null,after);found.push(...p.results);after=p.nextCursor}while(after);
 assert.equal(found.length,66);const person=found.filter(r=>r.sources.includes('fitp'));assert.equal(person.length,1);assert.ok(person[0].sources.includes('tennis-europe'));
}finally{d.close()}});
test('repeated same-circuit observations collapse and selected source keeps all official profile links',async()=>{const d=database();try{
 const guid='12345678-1234-1234-1234-123456789abc';
 for(const [key,circuit,id]of [['f','fitp','123456'],['e','tennis-europe',guid],['retry','tennis-europe','']])d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',[key,circuit,id,'DARKO SARTORI','Darko Sartori','{"birthYear":2010,"nationality":"ITA"}']);
 const page=await paginatedPlayerSearch(d.db,'Darko Sartori',null);assert.equal(page.results.length,1);assert.equal(page.results[0].circuitProfiles.length,2);
 const {searchIdentityProfile}=await import('../lib/paginated-player-search.mjs');const person=await searchIdentityProfile(d.db,'Darko Sartori','retry');assert.equal(person.sourceCircuit,'tennis-europe');assert.equal(person.circuitProfiles.length,2);assert.ok(person.circuitProfiles.some(p=>p.url.endsWith(guid)));
}finally{d.close()}});
