import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './search-sqlite-fixture.mjs';import {syncPlayerIdentities} from '../scripts/sync-player-identities.mjs';import {paginatedPlayerSearch} from '../lib/paginated-player-search.mjs';import {buildIdentityMapping} from '../lib/player-identity-mapping.mjs';import {storedIdentity,mappedPlayerId,mappedProfiles} from '../lib/player-identity-lookup.mjs';
const guid='12345678-1234-1234-1234-123456789abc';
function add(d,key,circuit,id,name='Darko Sartori',payload={birthYear:2010,nationality:'ITA'}){d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',[key,circuit,id,name.toUpperCase(),name,JSON.stringify(payload)]);}
test('D1_TEST_INITIAL_IMPORT: all acquired identities persist as one person with actual circuit links',async()=>{const d=database({identityMapping:true});try{
 add(d,'acquired|f','fitp','123456');add(d,'acquired|e','tennis-europe',guid,'Sartori Darko');const audit=await syncPlayerIdentities(d.query);assert.equal(audit.status,'ready');assert.equal(audit.missing_acquired,0);assert.equal(audit.people,1);assert.equal(audit.links,2);
 const results=await paginatedPlayerSearch(d.db,'Darko',null);assert.equal(results.results.length,1);assert.equal(results.results[0].circuitProfiles.length,2);const person=await storedIdentity(d.db,'acquired|f');assert.equal(person.canonicalId,(await storedIdentity(d.db,'acquired|e')).canonicalId);
}finally{d.close()}});
test('D1_TEST_IDENTICAL_ZERO_WRITES: unchanged mapping performs no mutations',async()=>{const d=database({identityMapping:true});try{add(d,'acquired|f','fitp','123456');await syncPlayerIdentities(d.query);const before=d.writes();const replay=await syncPlayerIdentities(d.query);assert.equal(replay.writes,0);assert.equal(d.writes(),before);}finally{d.close()}});
test('D1_TEST_REAL_DELTAS_ONLY: new circuit joins stable existing person and keeps old links',async()=>{const d=database({identityMapping:true});try{add(d,'acquired|f','fitp','123456');await syncPlayerIdentities(d.query);const first=await storedIdentity(d.db,'acquired|f');add(d,'acquired|e','tennis-europe',guid);await syncPlayerIdentities(d.query);assert.equal((await storedIdentity(d.db,'acquired|e')).canonicalId,first.canonicalId);assert.equal((await paginatedPlayerSearch(d.db,'Darko',null)).results[0].sources.length,2);}finally{d.close()}});
test('D1_TEST_INCOMPLETE_SOURCE_GUARD: incomplete input cannot replace the map',()=>{assert.throws(()=>buildIdentityMapping([],{sourceComplete:false}),/incomplete/);assert.throws(()=>buildIdentityMapping([{source_key:'bad',payload:'not json'}]),/incomplete/)});
test('homonyms with distinct official IDs remain separate; same official ID joins corrected name',async()=>{const d=database({identityMapping:true});try{add(d,'a','itf','800123456','Same Name',{nationality:'ITA',birthYear:2010});add(d,'b','itf','800123457','Same Name',{nationality:'SUI',birthYear:2011});add(d,'c','itf','800123456','Corrected Name',{nationality:'ITA',birthYear:2010});await syncPlayerIdentities(d.query);assert.notEqual((await storedIdentity(d.db,'a')).canonicalId,(await storedIdentity(d.db,'b')).canonicalId);assert.equal((await storedIdentity(d.db,'a')).canonicalId,(await storedIdentity(d.db,'c')).canonicalId);}finally{d.close()}});
test('configured identity alias remains stable and user membership is not shared across accounts',async()=>{const d=database({identityMapping:true});try{add(d,'acquired|f','fitp','123456');d.execute('INSERT INTO app_players(id,payload,seq) VALUES(?,?,?)',['configured',JSON.stringify({name:'Darko Sartori',birthYear:2010,nationality:'ITA',membershipCard:'123456'}),1]);await syncPlayerIdentities(d.query);assert.equal((await mappedPlayerId(d.db,'acquired|f','not-linked')).playerId,'configured');assert.equal((await paginatedPlayerSearch(d.db,'Darko','not-linked')).results[0].courtwatchId,'');}finally{d.close()}});

test('incremental name correction follows the official ID and preserves other circuit links',async()=>{const d=database({identityMapping:true});try{add(d,'a','fitp','123456');add(d,'b','tennis-europe',guid);await syncPlayerIdentities(d.query);const before=await storedIdentity(d.db,'a');d.execute('UPDATE search_acquired_players SET display_name=?,normalized_name=? WHERE source_key=?',['Corrected Name','CORRECTED NAME','a']);await syncPlayerIdentities(d.query);assert.equal((await storedIdentity(d.db,'a')).canonicalId,before.canonicalId);assert.equal((await storedIdentity(d.db,'b')).canonicalId,before.canonicalId);}finally{d.close()}});
test('failed mapping writes retain queue; concurrent source revision remains pending',async()=>{const d=database({identityMapping:true});try{add(d,'a','fitp','123456');await assert.rejects(syncPlayerIdentities(async sql=>{if(sql.includes('INSERT INTO player_identity_people'))throw Error('simulated write failure');return d.query(sql)}),/simulated/);assert.equal((await d.query('SELECT COUNT(*) AS n FROM player_identity_pending_sources'))[0].n,1);let changed=false;const audit=await syncPlayerIdentities(async sql=>{if(!changed&&sql.startsWith('DELETE FROM player_identity_pending_sources')){changed=true;d.execute('UPDATE search_acquired_players SET payload=? WHERE source_key=?',[JSON.stringify({birthYear:2010,nationality:'ITA',club:'Updated'}),'a']);}return d.query(sql)});assert.equal(audit.status,'pending');assert.equal(audit.pending,1);assert.equal((await syncPlayerIdentities(d.query)).status,'ready');}finally{d.close()}});

test('canonical pagination reaches all players and profile batches exceed the D1 parameter ceiling safely',async()=>{const d=database({identityMapping:true});try{const values=[];for(let i=0;i<137;i++){const name='Test '+String(i).padStart(3,'0');values.push(`('p${i}','itf','${800100000+i}','${name.toUpperCase()}','${name}','{"nationality":"ITA"}')`);}await d.query('INSERT INTO search_acquired_players VALUES '+values.join(',')+';');await syncPlayerIdentities(d.query);let cursor='',people=[];do{const page=await paginatedPlayerSearch(d.db,'Test',null,cursor);people.push(...page.results);cursor=page.nextCursor;}while(cursor);assert.equal(people.length,137);assert.equal(new Set(people.map(p=>p.canonicalId)).size,137);const profiles=await mappedProfiles(d.db,people.map(p=>({...p,id:p.canonicalId})));assert.equal(profiles.size,137);assert.ok([...profiles.values()].every(p=>p.length===1&&p[0].circuit==='itf'));}finally{d.close()}});

test('later configured identity retains old aliases and circuit selections reuse the account player',async()=>{const d=database({identityMapping:true});try{add(d,'acquired|f','fitp','123456');await syncPlayerIdentities(d.query);const first=await storedIdentity(d.db,'acquired|f');d.execute('INSERT INTO user_app_players(user_id,courtwatch_id,created_at) VALUES(?,?,?)',['owner',first.canonicalId,'2026-10-09']);d.execute('INSERT INTO app_players(id,payload,seq) VALUES(?,?,?)',['configured',JSON.stringify({name:'Darko Sartori',birthYear:2010,nationality:'ITA',membershipCard:'123456'}),1]);add(d,'acquired|e','tennis-europe',guid);await syncPlayerIdentities(d.query);assert.equal((await storedIdentity(d.db,first.canonicalId)).canonicalId,'configured');assert.equal((await mappedPlayerId(d.db,'acquired|e','owner')).playerId,first.canonicalId);assert.equal((await mappedPlayerId(d.db,'acquired|e','other')).playerId,'configured');}finally{d.close()}});
