import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './search-sqlite-fixture.mjs';
import {storedIdentity,mappedProfiles} from '../lib/player-identity-lookup.mjs';
function seed(d,id='canonical',source='source',alias='alias'){
 const payload=JSON.stringify({canonicalId:id,name:'Test Person',circuitProfiles:[{circuit:'fitp',url:'https://www.fitp.it/Pagina-Giocatore/?cardNumber=MTIzNDU2'}]});
 d.execute('INSERT INTO player_identity_people VALUES(?,?,?)',[id,'PERSON TEST',payload]);d.execute('INSERT INTO player_circuit_identities(source_key,canonical_id,name_key,circuit,official_id,normalized_name,display_name) VALUES(?,?,?,?,?,?,?)',[source,id,'PERSON TEST','fitp','123456','TEST PERSON','Test Person']);d.execute('INSERT INTO player_identity_aliases VALUES(?,?)',[alias,id]);
}
function traced(d){const calls=[];return{calls,db:{prepare(sql){return{bind(...values){calls.push({sql,values});return d.db.prepare(sql).bind(...values)}}}}};}
function indexedPlans(d,calls){for(const {sql,values}of calls){const plan=d.execute('EXPLAIN QUERY PLAN '+sql,values).map(r=>r.detail);assert.ok(!plan.some(p=>/\bSCAN (?:p|l|a|live)\b/.test(p)),plan.join('\n'));assert.ok(plan.some(p=>/USING (?:COVERING )?INDEX/.test(p)),plan.join('\n'));}}
test('single identity resolves by primary-key probes without scanning the player map',async()=>{const d=database({identityMapping:true});try{seed(d);const t=traced(d);for(const key of ['canonical','source','alias'])assert.equal((await storedIdentity(t.db,key)).canonicalId,'canonical');indexedPlans(d,t.calls);assert.equal(await storedIdentity(t.db,'absent'),null);}finally{d.close()}});
test('profile batches probe only requested source/alias keys with one JSON bind',async()=>{const d=database({identityMapping:true});try{seed(d);const players=Array.from({length:237},()=>({id:'alias',sourceKey:'source'})),t=traced(d);const profiles=await mappedProfiles(t.db,players);assert.equal(profiles.size,237);assert.equal(t.calls.length,3);assert.ok(t.calls.every(c=>c.values.length===1));indexedPlans(d,t.calls);}finally{d.close()}});
test('known profiles stay available while new unrelated identities await synchronization',async()=>{const d=database({identityMapping:true});try{seed(d);d.execute('INSERT INTO player_identity_pending_sources(source_table,source_key) VALUES(?,?)',['search_acquired_players','unrelated']);const player={id:'alias'};assert.equal((await mappedProfiles(d.db,[player])).get(player)[0].circuit,'fitp');assert.equal((await mappedProfiles(d.db,[{id:'unknown'}])).size,0);}finally{d.close()}});
test('orphan old canonical rows do not conflict with redirected aliases; contradictory keys stay ambiguous',async()=>{const d=database({identityMapping:true});try{seed(d,'new','source','old');d.execute('INSERT INTO player_identity_people VALUES(?,?,?)',['old','PERSON TEST','{"canonicalId":"old"}']);assert.equal((await storedIdentity(d.db,'old')).canonicalId,'new');seed(d,'other','other-source','other-alias');assert.equal((await mappedProfiles(d.db,[{id:'old',sourceKey:'other-source'}])).size,0);}finally{d.close()}});
test('personal Europe history uses the normalized-name expression index, preserving mixed case',async()=>{const d=database({identityMapping:true});try{d.execute('CREATE INDEX match_participants_lower_name_match ON match_participants(lower(normalized_name),match_id)');d.execute('INSERT INTO matches(id,tournament_id,circuit,payload) VALUES(?,?,?,?)',['m','t','tennis-europe','{}']);d.execute('INSERT INTO match_participants(match_id,participant_key,display_name,normalized_name,team_index,payload) VALUES(?,?,?,?,?,?)',['m','p','Test Person','Test Person',0,'{}']);const sql="SELECT DISTINCT m.id FROM match_participants self JOIN matches m ON m.id=self.match_id WHERE lower(self.normalized_name) IN (?,?) AND m.circuit='tennis-europe' AND m.id>? ORDER BY m.id LIMIT 250",values=['test person','person test',''];assert.equal(d.execute(sql,values).length,1);const plan=d.execute('EXPLAIN QUERY PLAN '+sql,values).map(r=>r.detail);assert.ok(plan.some(p=>/SEARCH self USING (?:COVERING )?INDEX match_participants_lower_name_match/.test(p)),plan.join('\n'));assert.ok(!plan.some(p=>/SCAN self/.test(p)),plan.join('\n'));}finally{d.close()}});
