import test from 'node:test';import assert from 'node:assert/strict';
import {profileEvidence,recoverProfileEvidence} from '../lib/player-profile-evidence.mjs';
import {acquiredPlayer} from '../lib/acquired-player-index.mjs';
import {buildIdentityMapping} from '../lib/player-identity-mapping.mjs';
import {database} from './search-sqlite-fixture.mjs';
import {recoverMissingProfiles,syncPlayerIdentities,profileRecoveryAudit} from '../scripts/sync-player-identities.mjs';
function seed(d,payload='{}'){d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['acquired|fitp|name:test','fitp','','TEST PERSON','Test Person',payload]);}
function match(d,id='123456'){d.execute('INSERT INTO matches(id,tournament_id,circuit,payload) VALUES(?,?,?,?)',['m','t','fitp','{}']);d.execute('INSERT INTO match_participants(match_id,participant_key,source_player_id,display_name,normalized_name,nationality,team_index,payload) VALUES(?,?,?,?,?,?,?,?)',['m','p',id,'Test Person','TEST PERSON','ITA',0,'{"birthYear":2010}']);}
test('raw circuit IDs and exact official URLs survive acquired indexing; draw-local IDs do not',()=>{assert.equal(acquiredPlayer('fitp',{name:'Test Person',source_player_id:'123456'}).officialId,'123456');assert.equal(profileEvidence('itf',{name:'Test Person',profileSync:{itf:{worldTennisId:'800123456'}},nationality:'ITA'}).officialId,'800123456');assert.equal(acquiredPlayer('itf',{name:'Test',id:'local-draw-1234'}).officialId,'');assert.equal(acquiredPlayer('tennis-europe',{name:'Test',id:'1234'}).officialId,'');assert.equal(profileEvidence('itf',{officialId:'800123456',profileUrl:'https://www.itftennis.com/en/players/test/800123457/ita/jt/s/overview/'}),null);});
test('compatible same-identity evidence fills an ITF country; local aliases inherit one real profile',()=>{const rows=[{source_key:'a',circuit:'itf',official_id:'800123456',display_name:'Test Person',payload:'{}'},{source_key:'b',circuit:'itf',official_id:'',display_name:'Person Test',payload:'{"nationality":"ITA","profileUrl":"https://www.itftennis.com/en/players/test-person/800123456/ita/jt/s/overview/"}'}];const map=buildIdentityMapping(rows);assert.equal(map.people.length,1);assert.ok(map.links.every(l=>l.profile_url&&l.official_id==='800123456'));});
test('conflicting official IDs, births or countries cannot be filled by name alone',()=>{const a={name:'Test Person',birthYear:2010,nationality:'ITA'};assert.equal(recoverProfileEvidence('fitp',a,[{...a,officialId:'123456'},{...a,officialId:'123457'}]),null);assert.equal(recoverProfileEvidence('fitp',a,[{...a,birthYear:2011,officialId:'123456'}]),null);assert.equal(recoverProfileEvidence('fitp',a,[{...a,nationality:'SUI',officialId:'123456'}]),null);});
test('D1_TEST_INITIAL_IMPORT: recovery uses acquired match evidence and remaps source without losing its key',async()=>{const d=database({identityMapping:true});try{seed(d,'{"birthYear":2010,"nationality":"ITA"}');match(d);await syncPlayerIdentities(d.query);const audit=await recoverMissingProfiles(d.query);assert.equal(audit.repaired,1);await syncPlayerIdentities(d.query);const row=(await d.query('SELECT * FROM player_circuit_identities'))[0];assert.equal(row.source_key,'acquired|fitp|name:test');assert.equal(row.official_id,'123456');assert.ok(row.profile_url);assert.equal((await profileRecoveryAudit(d.query)).unresolved,0);}finally{d.close()}});
test('D1_TEST_IDENTICAL_ZERO_WRITES: unresolved replay has no writes or participant rescans',async()=>{const d=database({identityMapping:true});try{seed(d);await syncPlayerIdentities(d.query);assert.equal((await recoverMissingProfiles(d.query)).repaired,0);const before=d.writes(),sql=[];const replay=await recoverMissingProfiles(async s=>{sql.push(s);return d.query(s)});assert.equal(replay.examined,0);assert.equal(d.writes(),before);assert.ok(sql.every(s=>!s.includes('FROM match_participants')));}finally{d.close()}});
test('D1_TEST_REAL_DELTAS_ONLY: changed source evidence is retried without rewriting unrelated sources',async()=>{const d=database({identityMapping:true});try{seed(d);await syncPlayerIdentities(d.query);await recoverMissingProfiles(d.query);d.execute('UPDATE search_acquired_players SET payload=? WHERE source_key=?',['{"membershipCard":"123456"}','acquired|fitp|name:test']);const result=await recoverMissingProfiles(d.query);assert.equal(result.repaired,1);assert.equal((await d.query('SELECT COUNT(*) AS n FROM search_acquired_players'))[0].n,1);}finally{d.close()}});
test('D1_TEST_INCOMPLETE_SOURCE_GUARD: failed repair writes cannot checkpoint the source',async()=>{const d=database({identityMapping:true});try{seed(d);match(d);await syncPlayerIdentities(d.query);await assert.rejects(recoverMissingProfiles(async s=>{if(s.startsWith('UPDATE search_acquired_players'))throw Error('failed repair');return d.query(s)}),/failed repair/);assert.equal((await d.query('SELECT COUNT(*) AS n FROM player_profile_recovery_checked'))[0].n,0);}finally{d.close()}});

test('a concurrent source metadata update survives a delayed profile repair',async()=>{const d=database({identityMapping:true});try{seed(d);match(d);await syncPlayerIdentities(d.query);let changed=false;await recoverMissingProfiles(async sql=>{if(!changed&&sql.startsWith('UPDATE search_acquired_players')){changed=true;d.execute('UPDATE search_acquired_players SET payload=? WHERE source_key=?',['{"club":"New club"}','acquired|fitp|name:test']);}return d.query(sql)});assert.equal(JSON.parse((await d.query('SELECT payload FROM search_acquired_players'))[0].payload).club,'New club');assert.equal((await recoverMissingProfiles(d.query)).examined,1);}finally{d.close()}});
