import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './search-sqlite-fixture.mjs';
import {syncPlayerIdentities,addD1Metrics} from '../scripts/sync-player-identities.mjs';
import {identityMappingSql} from '../lib/player-identity-mapping.mjs';
const add=d=>d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['a','fitp','123456','DARKO SARTORI','Darko Sartori',JSON.stringify({birthYear:2010,nationality:'ITA'})]);
test('diagnostic and ranking changes do not queue; club and birth changes do',async()=>{const d=database({identityMapping:true});try{add(d);await syncPlayerIdentities(d.query);for(const key of ['updatedAt','lastObservedAt','ranking','diagnostics']){d.execute('UPDATE search_acquired_players SET payload=json_set(payload,?,?) WHERE source_key=?',['$.'+key,'new','a']);assert.equal((await d.query('SELECT COUNT(*) AS n FROM player_identity_pending_sources'))[0].n,0);}for(const [key,value]of [['club','Lecco'],['birthYear',2011]]){d.execute('UPDATE search_acquired_players SET payload=json_set(payload,?,?) WHERE source_key=?',['$.'+key,value,'a']);assert.equal((await d.query('SELECT COUNT(*) AS n FROM player_identity_pending_sources'))[0].n,1);await syncPlayerIdentities(d.query);}}finally{d.close()}});
test('guard blocks before writes and preserves queue; explicit bulk option resumes',async()=>{const d=database({identityMapping:true});try{add(d);const n=d.writes();await assert.rejects(syncPlayerIdentities(d.query,{maxChanges:0}),/identity_bulk_write_blocked/);assert.equal(d.writes(),n);assert.equal((await d.query('SELECT COUNT(*) AS n FROM player_identity_pending_sources'))[0].n,1);await syncPlayerIdentities(d.query,{maxChanges:0,allowBulk:true});const after=d.writes();assert.equal((await syncPlayerIdentities(d.query)).writes,0);assert.equal(d.writes(),after);}finally{d.close()}});
test('payload-only delta avoids updates to indexed name column',()=>{const before={canonical_id:'a',name_key:'darko',payload:'{}'},after={...before,payload:'{"club":"Lecco"}'},plans={people:{inserts:[],updates:[{before,after}]},links:{inserts:[],updates:[]},aliases:{inserts:[],updates:[]}};let sql=identityMappingSql({plans})[0];assert.match(sql,/SET payload=excluded.payload/);assert.doesNotMatch(sql,/SET.*name_key=excluded/);plans.people.updates[0].after={...after,name_key:'corrected'};assert.match(identityMappingSql({plans})[0],/name_key=excluded.name_key/);});
test('metrics report actual D1 rows across statement results',()=>{const m={rowsWritten:0,rowsRead:0};addD1Metrics(m,{result:[{meta:{rows_written:42,rows_read:12}},{meta:{rows_written:3,rows_read:7}}]});assert.deepEqual(m,{rowsWritten:45,rowsRead:19});});
