import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './search-sqlite-fixture.mjs';import {syncPlayerIdentities,recoverMissingProfiles} from '../scripts/sync-player-identities.mjs';import {acquiredPlayer} from '../lib/acquired-player-index.mjs';import {matchProfileCandidates,profileEvidence} from '../lib/player-profile-evidence.mjs';
const guid='12345678-1234-1234-1234-123456789abc';
const add=(d,c,id,name)=>d.execute('INSERT INTO search_acquired_players VALUES(?,?,?,?,?,?)',['a',c,id,name.toUpperCase(),name,'{}']);
test('native ITF country/profile and TE participant IDs survive future indexing',()=>{let p=acquiredPlayer('itf',{playerId:'800543439',name:'Aruzhan Nuranbay',nationalityCode:'KAZ',profileLink:'https://www.itftennis.com/en/players/aruzhan-nuranbay/800543439/kaz/jt/s/overview/'});assert.equal(p.officialId,'800543439');assert.equal(p.payload.nationality,'KAZ');assert.match(p.payload.profileUrl,/\/kaz\//);p=acquiredPlayer('tennis-europe',{participantId:guid,playerName:'Oliwier Kowzan',countryCode:'POL'});assert.equal(p.officialId,guid);assert.equal(p.payload.nationality,'POL');assert.match(p.payload.profileUrl,/player-profile/);});
test('rank history repairs TE missing ID and replay performs zero writes',async()=>{const d=database({identityMapping:true});try{add(d,'tennis-europe','','Oliwier Kowzan');await syncPlayerIdentities(d.query);d.execute('INSERT INTO tennis_europe_ranking_history VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[guid,'2026-10-01','pub','week','B14',50,1,'Oliwier Kowzan','OLIWIER KOWZAN','POL','https://te.tournamentsoftware.com/ranking', 'today']);const r=await recoverMissingProfiles(d.query);assert.equal(r.repaired,1);await syncPlayerIdentities(d.query);assert.equal((await d.query("SELECT official_id FROM search_acquired_players WHERE source_key='a'"))[0].official_id,guid);const n=d.writes();assert.equal((await recoverMissingProfiles(d.query)).examined,0);assert.equal(d.writes(),n);}finally{d.close()}});
test('raw match native nationality fixes ITF ID-only link; old checkpoint is safely retried once',async()=>{const d=database({identityMapping:true});try{add(d,'itf','800543439','Aruzhan Nuranbay');await syncPlayerIdentities(d.query);d.execute("INSERT INTO player_profile_recovery_checked(source_table,source_key,source_payload) VALUES('search_acquired_players','a','{}')");const candidates=matchProfileCandidates('itf',{teams:[{players:[{name:'Aruzhan Nuranbay',playerId:'800543439',nationalityCode:'KAZ'}]}]});assert.equal(profileEvidence('itf',candidates[0]).nationality,'KAZ');const query=async sql=>sql.includes('FROM match_participants p JOIN matches')?[{match_id:'m',participant_key:'p',source_player_id:'800543439',display_name:'Aruzhan Nuranbay',nationality:'',payload:'{}',circuit:'itf',match_payload:JSON.stringify({teams:[{players:[{name:'Aruzhan Nuranbay',playerId:'800543439',nationalityCode:'KAZ'}]}]})}]:d.query(sql);assert.equal((await recoverMissingProfiles(query)).repaired,1);await syncPlayerIdentities(d.query);assert.match((await d.query("SELECT profile_url FROM player_circuit_identities WHERE source_key='a'"))[0].profile_url,/\/kaz\//);const n=d.writes();assert.equal((await recoverMissingProfiles(query)).examined,0);assert.equal(d.writes(),n);}finally{d.close()}});
test('conflicting rank profile IDs remain unresolved and automatic batch honors its bound',async()=>{const d=database({identityMapping:true});try{add(d,'tennis-europe','','Oliwier Kowzan');await syncPlayerIdentities(d.query);for(const id of [guid,'22345678-1234-1234-1234-123456789abc'])d.execute('INSERT INTO tennis_europe_player_aliases VALUES(?,?,?,?,?)',[id,'OLIWIER KOWZAN','POL',null,'today']);assert.equal((await recoverMissingProfiles(d.query,{limit:1})).repaired,0);assert.equal((await d.query("SELECT official_id FROM search_acquired_players WHERE source_key='a'"))[0].official_id,'');}finally{d.close()}});
test('new official evidence invalidates only unresolved checkpoint and enables future association',async()=>{const d=database({identityMapping:true});try{add(d,'tennis-europe','','Oliwier Kowzan');await syncPlayerIdentities(d.query);assert.equal((await recoverMissingProfiles(d.query)).repaired,0);d.execute('INSERT INTO tennis_europe_player_aliases VALUES(?,?,?,?,?)',[guid,'OLIWIER KOWZAN','POL',null,'today']);assert.equal((await d.query("SELECT evidence_version FROM player_profile_recovery_checked WHERE source_key='a'"))[0].evidence_version,0);assert.equal((await recoverMissingProfiles(d.query)).repaired,1);await syncPlayerIdentities(d.query);assert.match((await d.query("SELECT profile_url FROM player_circuit_identities WHERE source_key='a'"))[0].profile_url,/player-profile/);const n=d.writes();await recoverMissingProfiles(d.query);assert.equal(d.writes(),n);}finally{d.close()}});
