const state={data:null,month:new Date(),week:new Date(),selected:new Set()};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const iso=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)},monday=d=>{const x=new Date(d),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(12,0,0,0);return x},addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},fmtDate=d=>new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'short'}).format(d),initials=n=>n.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
const sourceLabel=x=>x.sourceName||x.circuit||'Fonte ufficiale';
const sourceLinkLabel=x=>sourceLabel(x).includes('ITF')?'Apri ITF ↗':sourceLabel(x).includes('Tennis Europe')?'Apri Tennis Europe ↗':'Apri P.U.C. FITP ↗';
const overlaps=(t,start,end)=>t.status!=='eliminated'&&t.status!=='finished'&&(!t.startDate||t.startDate<=end)&&(!t.endDate||t.endDate>=start);
function renderFilters(){const ps=state.data.players||[];$('playerFilters').innerHTML=ps.map(p=>`<button class="chip ${state.selected.has(p.id)?'selected':''}" data-filter="${esc(p.id)}">${esc(p.name)}</button>`).join('');$('toggleAll').textContent=state.selected.size?'Deseleziona tutti':'Seleziona tutti';document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.selected.has(b.dataset.filter)?state.selected.delete(b.dataset.filter):state.selected.add(b.dataset.filter);renderHome()})}
function dailyTournamentGroups(day){const map=new Map();for(const t of state.data.tournaments||[]){if(!state.selected.has(t.playerId)||!overlaps(t,day,day))continue;const key=`${t.name}|${t.location||''}`;const g=map.get(key)||{name:t.name,location:t.location||'Luogo da pubblicare',players:[],playerIds:[]};if(!g.players.includes(t.playerName))g.players.push(t.playerName);if(!g.playerIds.includes(t.playerId))g.playerIds.push(t.playerId);map.set(key,g)}return[...map.values()]}
function renderCalendar(){const base=new Date(state.month.getFullYear(),state.month.getMonth(),1,12),start=monday(base);$('monthTitle').textContent=new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(base).replace(/^./,c=>c.toUpperCase());let html='';for(let i=0;i<42;i++){const d=addDays(start,i),key=iso(d),groups=dailyTournamentGroups(key),matches=(state.data.matches||[]).filter(m=>m.date===key&&m.status!=='cancelled'&&state.selected.has(m.playerId));html+=`<div class="day ${d.getMonth()!==base.getMonth()?'out':''} ${key===iso(new Date())?'today':''}"><div class="date"><b>${d.getDate()}</b>${groups.length?`<span>${groups.length}</span>`:''}</div>${groups.slice(0,3).map(g=>`<button class="event" data-player="${esc(g.playerIds[0])}"><strong>${esc(g.name)}</strong><time>${esc(g.players.join(', '))}</time>${g.location?`<time>${esc(g.location)}</time>`:''}</button>`).join('')}${matches.length?`<div class="dayMatches">${matches.map(m=>`${esc(m.playerName)} · ${esc(m.time||'orario da pubblicare')}`).join('<br>')}</div>`:''}${groups.length>3?`<div class="event more">+${groups.length-3} tornei</div>`:''}</div>`}$('calendar').innerHTML=html;document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>openProfile(b.dataset.player))}
function renderWeek(){const start=monday(state.week),end=addDays(start,6),s=iso(start),e=iso(end);$('weekRange').textContent=`${fmtDate(start)} – ${fmtDate(end)}`;const map=new Map();for(const t of state.data.tournaments||[]){if(!state.selected.has(t.playerId)||!overlaps(t,s,e))continue;const key=`${t.name}|${t.location||''}`;if(!map.has(key))map.set(key,t)}const items=[...map.values()];$('weeklyActive').innerHTML=items.length?items.map(t=>`<div class="activeItem"><strong>${esc(t.name)}</strong><small>${esc(t.location||'Luogo da pubblicare')}</small></div>`).join(''):'<div class="empty">Nessun torneo previsto in questa settimana.</div>'}
function confirmedCount(id){return(state.data.tournaments||[]).filter(t=>t.playerId===id&&!['eliminated','finished'].includes(t.status)).length}
function renderPlayers(){const ps=state.data.players||[];$('playerTotal').textContent=ps.length;$('playersList').innerHTML=ps.map(p=>{const n=confirmedCount(p.id);return`<div class="playerRow" data-profile="${esc(p.id)}"><div class="avatar">${initials(p.name)}</div><div class="playerInfo"><strong>${esc(p.name)}</strong><small>${n?`${n} ${n===1?'torneo':'tornei'} monitorati`:'Verifica iscrizioni in corso'}</small></div><div class="arrow">›</div></div>`}).join('');document.querySelectorAll('[data-profile]').forEach(x=>x.onclick=()=>openProfile(x.dataset.profile))}
function renderAgenda(){const today=iso(new Date()),matches=(state.data.matches||[]).filter(m=>m.date===today&&m.status!=='cancelled'&&state.selected.has(m.playerId)).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));$('agendaDate').textContent=new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('todayAgenda').innerHTML=matches.length?`<div class="agendaList">${matches.map(m=>`<div class="agendaItem" data-agenda-player="${esc(m.playerId)}"><div class="agendaTime">${esc(m.time||'—')}</div><div class="agendaInfo"><strong>${esc(m.playerName)}</strong><small>${esc(m.tournamentName)}${m.location?' · '+esc(m.location):''}${m.court?' · Campo '+esc(m.court):''}${m.opponent?' · vs '+esc(m.opponent):''}</small></div><span class="badge upcoming">Partita</span></div>`).join('')}</div>`:'<div class="empty">Nessuna partita prevista oggi.</div>';document.querySelectorAll('[data-agenda-player]').forEach(x=>x.onclick=()=>openProfile(x.dataset.agendaPlayer))}
function entryInfo(t){if(!t.entryStatus)return'';const position=t.entryPosition?` · posizione ${esc(t.entryPosition)}`:'';return`<div class="entryStatus"><b>${esc(t.entryStatus)}</b>${position}</div>`}
function renderHome(){renderFilters();renderAgenda();renderCalendar();renderWeek();renderPlayers()}
function openProfile(id){location.hash='player/'+encodeURIComponent(id)}
function renderProfile(id){const p=(state.data.players||[]).find(x=>x.id===id);if(!p){location.hash='';return}const tournaments=(state.data.tournaments||[]).filter(t=>t.playerId===id).sort((a,b)=>(a.startDate||'9999').localeCompare(b.startDate||'9999')),matches=(state.data.matches||[]).filter(m=>m.playerId===id&&m.status!=='cancelled').sort((a,b)=>`${a.date}${a.time||''}`.localeCompare(`${b.date}${b.time||''}`));$('profileContent').innerHTML=`<div class="card"><div class="profileHero"><div class="profileIdentity"><div class="avatar">${initials(p.name)}</div><div><h2>${esc(p.name)}</h2><p>${esc(p.club||'Giocatore monitorato')}</p></div></div><div class="profileStats"><div class="stat"><b>${tournaments.filter(t=>t.status==='active').length}</b><span>in corso</span></div><div class="stat"><b>${tournaments.filter(t=>t.status==='upcoming').length}</b><span>in programma</span></div><div class="stat"><b>${matches.length}</b><span>partite</span></div></div></div></div><div class="profileGrid"><div class="card"><div class="cardHead"><h3>Tornei</h3><span>${tournaments.length}</span></div>${tournaments.length?tournaments.map(t=>`<div class="listItem"><div class="listTop"><h4>${esc(t.name)}</h4><span class="badge ${t.status==='upcoming'?'upcoming':t.status==='eliminated'?'eliminated':''}">${t.status==='active'?'In gara':t.status==='upcoming'?'In programma':t.status==='eliminated'?'Eliminato':'Concluso'}</span></div><p>${esc(t.location||'Luogo da pubblicare')} · ${esc(t.startDate||'Data da pubblicare')}${t.endDate?' – '+esc(t.endDate):''}</p>${entryInfo(t)}${t.url?`<a class="sourceLink" href="${esc(t.url)}" target="_blank" rel="noopener">${sourceLinkLabel(t)}</a>`:''}</div>`).join(''):'<div class="empty">Verifica delle iscrizioni in corso.</div>'}</div><div class="card"><div class="cardHead"><h3>Partite programmate</h3><span>${matches.length}</span></div>${matches.length?matches.map(m=>`<div class="listItem"><div class="listTop"><h4>${esc(m.tournamentName)}</h4><span class="badge upcoming">${esc(m.date)}</span></div><p>${esc(m.time||'Orario da pubblicare')}${m.location?' · '+esc(m.location):''}${m.court?' · Campo '+esc(m.court):''}${m.opponent?' · vs '+esc(m.opponent):''}</p>${m.url?`<a class="sourceLink" href="${esc(m.url)}" target="_blank" rel="noopener">Apri P.U.C. FITP ↗</a>`:''}</div>`).join(''):'<div class="empty">Nessuna partita ancora inserita nell’ordine di gioco.</div>'}</div></div>`;$('homeView').classList.remove('active');$('profileView').classList.add('active')}
function route(){const m=location.hash.match(/^#player\/(.+)$/);if(m&&state.data)renderProfile(decodeURIComponent(m[1]));else{$('profileView').classList.remove('active');$('homeView').classList.add('active');if(state.data)renderHome()}}
$('prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};$('todayBtn').onclick=()=>{state.month=new Date();state.week=new Date();renderHome()};$('prevWeek').onclick=()=>{state.week=addDays(state.week,-7);renderWeek()};$('nextWeek').onclick=()=>{state.week=addDays(state.week,7);renderWeek()};$('toggleAll').onclick=()=>{state.selected.size?state.selected.clear():(state.data.players||[]).forEach(p=>state.selected.add(p.id));renderHome()};$('backHome').onclick=()=>location.hash='';addEventListener('hashchange',route);
async function load(){try{const r=await fetch('/data.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);state.data=await r.json();state.data.matches||=[];state.data.tournaments||=[];if(!state.selected.size)(state.data.players||[]).forEach(p=>state.selected.add(p.id));$('syncStatus').textContent='Vercel · '+(state.data.generatedAt?new Intl.DateTimeFormat('it-IT',{hour:'2-digit',minute:'2-digit'}).format(new Date(state.data.generatedAt)):'sincronizzato');route()}catch(e){$('syncStatus').textContent='Vercel · dati non disponibili'}}load();setInterval(load,120000);
