import fs from 'node:fs/promises';
import { chromium } from 'playwright';
const ITF_SITE=['https:','','www.itftennis.com'].join('/');
const API=ITF_SITE+'/tennis/api/TournamentApi';
const cfg=JSON.parse(await fs.readFile('players.json','utf8'));
const data=JSON.parse(await fs.readFile('data.json','utf8'));
const players=(cfg.players||[]).filter(p=>(p.circuits||[]).some(c=>String(c).toUpperCase()==='ITF'));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
const today=new Date().toISOString().slice(0,10),from='2026-06-20',to=new Date(Date.now()+240*864e5).toISOString().slice(0,10),now=new Date().toISOString(),errors=[],hits=[],samples=[],tournaments=[];
async function calendarJson(url){const r=await fetch(url,{headers:{accept:'application/json','user-agent':'Mozilla/5.0 CourtWatchITF/3.0','referer':ITF_SITE+'/'}}),text=await r.text();if(!r.ok)throw Error(`${r.status} ${text.slice(0,160)}`);return JSON.parse(text)}
function objects(v,out=[]){if(Array.isArray(v)){for(const x of v)objects(x,out)}else if(v&&typeof v==='object'){out.push(v);for(const x of Object.values(v))objects(x,out)}return out}
function entryStatus(o){const s=norm(JSON.stringify(o));if(/MAIN DRAW|ACCEPTED|DIRECT ACCEPTANCE/.test(s))return'Main Draw';if(/QUALIFYING|QUALIFICATION/.test(s))return'Qualifying';if(/ALTERNATE|ALTERNATES|ALTERNATIVE/.test(s))return'Alternates';return'Iscritto'}
function position(o,st){const keys=Object.keys(o),k=keys.find(x=>/alternate.*(position|number|order)|acceptance.*position|list.*position|entry.*position/i.test(x))||keys.find(x=>/^(position|positionDisplay|order|listPosition|alternateNumber)$/i.test(x)),v=k?o[k]:null;if(v!==null&&v!==undefined&&/^\d{1,4}$/.test(String(v)))return Number(v);if(st==='Alternates'){const m=JSON.stringify(o).match(/(?:alternate|alt)[^0-9]{0,25}(\d{1,3})/i);if(m)return Number(m[1])}return null}
function publicUrl(t,key){let link=String(t.tournamentLink||t.url||'');if(!link)link='/en/tournament/x/x/2026/'+key+'/';if(!/^https?:/i.test(link))link=ITF_SITE+(link.startsWith('/')?'':'/')+link;return link.replace(/\/?$/,'/')+(link.includes('acceptance-list')?'':'acceptance-list/')}
for(let skip=0;skip<2000;skip+=100){try{const url=API+'/GetCalendar?circuitCode=JT&searchString=&skip='+skip+'&take=100&nationCodes=&zoneCodes=&dateFrom='+from+'&dateTo='+to+'&indoorOutdoor=&categories=&isOrderAscending=true&orderField=startDate&surfaceCodes=&singlesDrawFormat=',j=await calendarJson(url),items=j.items||j.Items||j.tournaments||j.Tournaments||[];tournaments.push(...items);if(items.length<100)break}catch(e){errors.push(`calendar ${skip}: ${e.message}`);break}}
for(const p of players)for(const c of p.confirmedOfficialTournaments||[]){const key=(c.url.match(/\/([^/]+)\/?$/)||[])[1];if(key&&!tournaments.some(t=>String(t.tournamentKey||t.TournamentKey).toLowerCase()===key.toLowerCase()))tournaments.unshift({tournamentKey:key,tournamentName:c.name,startDate:c.startDate,endDate:c.endDate,tournamentLink:c.url})}
const browser=await chromium.launch({headless:true});const ctx=await browser.newContext({locale:'en-GB',userAgent:'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36'});let index=0;
function record(j,t,key,url){if(samples.length<3)samples.push({tournamentKey:key,topKeys:Object.keys(j||{}),preview:JSON.stringify(j).slice(0,5000)});for(const o of objects(j)){const hay=norm(JSON.stringify(o));for(const p of players){const aliases=[p.name,...(p.aliases||[])].filter(a=>norm(a).split(' ').length>1);if(!aliases.some(a=>hay.includes(norm(a))))continue;const st=entryStatus(o),pos=position(o,st),id=key.toUpperCase();if(hits.some(h=>h.playerId===p.id&&h.tournamentKey===id))continue;hits.push({playerId:p.id,playerName:p.name,tournamentKey:id,tournamentName:t.tournamentName||t.name||id,location:t.location||t.venue||'',hostNation:t.hostNation||'',hostNationCode:t.hostNationCode||'',startDate:String(t.startDate||'').slice(0,10),endDate:String(t.endDate||'').slice(0,10),status:st,position:pos,url,observedAt:now})}}}
async function worker(){const page=await ctx.newPage();while(index<tournaments.length){const t=tournaments[index++],key=String(t.tournamentKey||t.TournamentKey||'').toLowerCase();if(!key)continue;const url=publicUrl(t,key);try{const responsePromise=page.waitForResponse(r=>r.url().includes('GetAcceptanceList'),{timeout:12000}).catch(()=>null);await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});const response=await responsePromise;let j=null;if(response){const text=await response.text();try{j=JSON.parse(text)}catch{errors.push(`${key}: risposta browser non JSON ${text.slice(0,120)}`)}}if(!j){const r=await ctx.request.get(API+'/GetAcceptanceList?tournamentKey='+encodeURIComponent(key)+'&circuitCode=JT',{headers:{accept:'application/json','referer':url,'x-requested-with':'XMLHttpRequest'}}),text=await r.text();try{j=JSON.parse(text)}catch{errors.push(`${key}: JSON non valido ${text.slice(0,120)}`)}}if(j)record(j,t,key,url);else{const body=await page.locator('body').innerText().catch(()=> '');for(const p of players){if(![p.name,...(p.aliases||[])].some(a=>norm(body).includes(norm(a))))continue;record([{name:p.name,status:/MAIN DRAW/i.test(body)?'Main Draw':/QUALIFYING/i.test(body)?'Qualifying':/ALTERNATE/i.test(body)?'Alternates':'Iscritto'}],t,key,url)}}catch(e){errors.push(`${key}: ${e.message}`)}}await page.close()}
await Promise.all(Array.from({length:3},worker));await browser.close();
for(const h of hits){const k=`${h.playerId}|itf-${h.tournamentKey}`,old=(data.tournaments||[]).find(t=>t.playerId===h.playerId&&t.itfTournamentKey===h.tournamentKey),value={key:k,playerId:h.playerId,playerName:h.playerName,name:h.tournamentName,location:h.location,sourceId:'itf',sourceName:'ITF',url:h.url.replace(/acceptance-list\/$/,''),startDate:h.startDate,endDate:h.endDate,status:h.endDate&&h.endDate<today?'finished':h.startDate&&h.startDate>today?'upcoming':'active',entryStatus:h.status,entryPosition:h.position,hostNation:h.hostNation,hostNationCode:h.hostNationCode,itfTournamentKey:h.tournamentKey,lastSeen:now};if(old)Object.assign(old,value);else(data.tournaments||=[]).push(value);data.entryStatuses=(data.entryStatuses||[]).filter(x=>!(x.playerId===h.playerId&&x.tournamentKey===k));data.entryStatuses.push({playerId:h.playerId,playerName:h.playerName,tournamentKey:k,tournamentName:h.tournamentName,sourceId:'itf',status:h.status,position:h.position,url:h.url,observedAt:now})}
data.generatedAt=now;data.itfEntryDiscovery={lastRun:now,status:tournaments.length?(errors.length?'partial':'complete'):'failed',coverageFrom:from,coverageUntil:to,tournamentsChecked:tournaments.length,playersChecked:players.length,entriesFound:hits.length,errors:errors.slice(0,100)};await fs.writeFile('data.json',JSON.stringify(data,null,2)+'\n');await fs.writeFile('itf-sync.json',JSON.stringify({...data.itfEntryDiscovery,hits,samples},null,2)+'\n');console.log(JSON.stringify(data.itfEntryDiscovery,null,2));if(!tournaments.length)process.exitCode=2;
