import{chromium}from'playwright';import fs from'node:fs/promises';import os from'node:os';import path from'node:path';import{execFile}from'node:child_process';import{promisify}from'node:util';import{URL}from'node:url';
const run=promisify(execFile),cfg=JSON.parse(await fs.readFile('players.json','utf8')),old=JSON.parse(await fs.readFile('data.json','utf8')),today=new Date().toISOString().slice(0,10),players=cfg.players||[];
const sources=[{id:'fitp-puc',name:'P.U.C. FITP',hosts:['fitp.it'],seeds:['https://www.fitp.it/Tornei/Ricerca-tornei?tournament=Junior%20Next%20Gen%20Brallo','https://www.fitp.it/Tornei/Ricerca-tornei']},{id:'tennis-europe',name:'Tennis Europe',hosts:['te.tournamentsoftware.com'],seeds:['https://te.tournamentsoftware.com/']},{id:'itf',name:'ITF',hosts:['itftennis.com'],seeds:['https://www.itftennis.com/en/tournament/j30-cuneo/ita/2026/j-j30-ita-2026-002/acceptance-list/']}];
for(const p of players){for(const[k,urls]of Object.entries(p.officialUrls||{})){const id=k==='fitp'?'fitp-puc':k==='tennisEurope'?'tennis-europe':'itf',s=sources.find(x=>x.id===id);for(const u of urls||[])if(u&&!s.seeds.includes(u))s.seeds.push(u)}sources.find(x=>x.id==='tennis-europe').seeds.push(`https://te.tournamentsoftware.com/find/player?q=${encodeURIComponent(p.name)}`);sources.find(x=>x.id==='itf').seeds.push(`https://www.itftennis.com/en/search/?q=${encodeURIComponent(p.name)}`)}
for(const t of old.tournaments||[]){const s=sources.find(x=>x.id===t.sourceId);if(s&&t.url&&!s.seeds.includes(t.url))s.seeds.push(t.url)}
const norm=s=>String(s||'').replace(/\s+/g,' ').trim(),up=s=>norm(s).toUpperCase(),abs=(h,b)=>{try{return new URL(h,b).href.split('#')[0]}catch{return null}},allowed=(url,s)=>{try{const h=new URL(url).hostname.replace(/^www\./,'');return s.hosts.some(x=>h.endsWith(x))}catch{return false}};
const months={gennaio:1,febbraio:2,marzo:3,aprile:4,maggio:5,giugno:6,luglio:7,agosto:8,settembre:9,ottobre:10,novembre:11,dicembre:12,january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
function dates(text){const a=[];for(const m of text.matchAll(/\b(20\d{2})-(\d{2})-(\d{2})\b/g))a.push(m[0]);for(const m of text.matchAll(/\b(\d{1,2})[\/.](\d{1,2})[\/.](20\d{2})\b/g))a.push(`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`);for(const m of text.toLowerCase().matchAll(/\b(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre|january|february|march|april|may|june|july|august|september|october|november|december)\s+(20\d{2})\b/g))a.push(`${m[3]}-${String(months[m[2]]).padStart(2,'0')}-${m[1].padStart(2,'0')}`);return[...new Set(a)].sort()}
function times(text){return[...new Set([...text.matchAll(/\b(?:ore|at|not before|nb)?\s*([01]?\d|2[0-3])[:.]([0-5]\d)\b/ig)].map(m=>`${m[1].padStart(2,'0')}:${m[2]}`))]}
function entry(text){let status=null;if(/main draw|tabellone principale|md\b/i.test(text))status='Main draw';else if(/qualifying|qualification|qualificazioni|quali\b|\bq\b/i.test(text))status='Qualifying';else if(/alternates?|alternate list|riserve|\balt\b/i.test(text))status='Alternates';const position=text.match(/(?:position|posizione|alternate|alt\.?|number|numero)[^0-9]{0,18}(\d{1,3})/i)?.[1]||null;return{status,position}}
function cleanTitle(t){return norm(t).replace(/\s*[|–-]\s*(FITP|Tennis Europe|ITF).*$/i,'').slice(0,180)||'Torneo'}
const tournaments=new Map((old.tournaments||[]).filter(t=>['fitp-puc','tennis-europe','itf'].includes(t.sourceId)).map(t=>[t.key,t])),matches=new Map((old.matches||[]).filter(m=>['fitp-puc','tennis-europe','itf'].includes(m.sourceId)).map(m=>[m.key,m])),entries=new Map((old.entryStatuses||[]).map(e=>[`${e.playerId}|${e.tournamentKey}`,e])),findings=[],states=[],tmp=await fs.mkdtemp(path.join(os.tmpdir(),'courtwatch-'));
function processText(source,url,title,text){text=norm(text);if(!text)return;const allDates=dates(text),schedulePage=/ordine di gioco|order of play|programma incontri|schedule|not before|starting at|campo|court/i.test(`${title} ${url} ${text.slice(0,1800)}`);for(const p of players){let at=-1;for(const a of p.aliases||[p.name]){at=up(text).indexOf(up(a));if(at>=0)break}if(at<0)continue;const ctx=norm(text.slice(Math.max(0,at-700),at+1600)),e=entry(ctx),ctxDates=dates(ctx),ctxTimes=times(ctx),observedAt=new Date().toISOString(),baseTour=[...tournaments.values()].find(t=>t.playerId===p.id&&t.sourceId===source.id&&(!t.url||url.includes(new URL(t.url).pathname)))||[...tournaments.values()].find(t=>t.playerId===p.id&&t.sourceId===source.id),tourName=baseTour?.name||cleanTitle(title),location=baseTour?.location||'Luogo da pubblicare',tourKey=baseTour?.key||`${source.id}|${p.id}|${tourName.toLowerCase().replace(/\W+/g,'-')}`;findings.push({key:`${source.id}|${p.id}|${url}`,playerId:p.id,playerName:p.name,sourceId:source.id,sourceName:source.name,title:cleanTitle(title),url,snippet:ctx.slice(0,900),observedAt,entryStatus:e.status,entryPosition:e.position});if(e.status){entries.set(`${p.id}|${tourKey}`,{playerId:p.id,playerName:p.name,tournamentKey:tourKey,tournamentName:tourName,sourceId:source.id,status:e.status,position:e.position,url,observedAt});if(baseTour){baseTour.entryStatus=e.status;baseTour.entryPosition=e.position;baseTour.lastSeen=observedAt}}
const ds=ctxDates.length?ctxDates:allDates;if(!baseTour&&ds.length>=2&&!/ricerca|search/i.test(title)){tournaments.set(tourKey,{key:tourKey,playerId:p.id,playerName:p.name,name:tourName,location,sourceId:source.id,sourceName:source.name,url,startDate:ds[0],endDate:ds.at(-1),status:ds.at(-1)<today?'finished':ds[0]>today?'upcoming':'active',lastSeen:observedAt})}
if(schedulePage&&ctxTimes.length){const d=ds.find(x=>x>=today)||ds[0];if(d){const tm=ctxTimes[0],court=ctx.match(/(?:campo|court)\s*(?:n\.?\s*)?([A-Za-z0-9-]+)/i)?.[1]||null,op=ctx.match(/(?:vs\.?|contro)\s+([A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ' -]{3,50})/i)?.[1]?.trim()||null,key=`${source.id}|${p.id}|${d}|${tm}|${tourName}`;matches.set(key,{key,playerId:p.id,playerName:p.name,tournamentName:tourName,location,date:d,time:tm,court,opponent:op,url,sourceId:source.id,sourceName:source.name,status:'scheduled',lastSeen:observedAt});for(const[mKey,m]of matches)if(m!==matches.get(key)&&m.playerId===p.id&&m.date===d&&m.sourceId===source.id&&!m.time){m.time=tm;m.court=court;m.opponent=op;m.url=url;m.lastSeen=observedAt}}}}
}
const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({locale:'it-IT',timezoneId:'Europe/Rome',userAgent:'Mozilla/5.0 (compatible; CourtWatchOfficialMonitor/5.0)'});
for(const source of sources){const queue=[...new Set(source.seeds)].map(url=>({url,depth:0})),seen=new Set(),errors=[];while(queue.length&&seen.size<45){const item=queue.shift();if(!item||seen.has(item.url)||!allowed(item.url,source))continue;seen.add(item.url);if(/\.pdf(?:\?|$)/i.test(item.url)){try{const file=path.join(tmp,`${source.id}-${seen.size}.pdf`),txt=file+'.txt',r=await fetch(item.url);await fs.writeFile(file,Buffer.from(await r.arrayBuffer()));await run('pdftotext',['-layout',file,txt]);processText(source,item.url,path.basename(new URL(item.url).pathname),await fs.readFile(txt,'utf8'))}catch(e){errors.push(String(e.message||e).slice(0,160))}continue}const page=await ctx.newPage(),responseTasks=[];page.on('response',res=>{const ct=res.headers()['content-type']||'';if(/json|text\//i.test(ct)&&/api|search|tournament|draw|schedule|accept|order|competition/i.test(res.url()))responseTasks.push((async()=>{try{const text=await res.text();if(text.length<4000000)processText(source,res.url(),await page.title().catch(()=>res.url()),text)}catch{}})())});try{await page.goto(item.url,{waitUntil:'domcontentloaded',timeout:35000});await page.waitForTimeout(5000);const title=norm(await page.title()),body=await page.locator('body').innerText({timeout:12000}).catch(()=>''),links=await page.locator('a[href]').evaluateAll(as=>as.map(a=>({href:a.getAttribute('href'),text:(a.textContent||'').trim()})));processText(source,item.url,title,body);await Promise.allSettled(responseTasks);if(item.depth<2)for(const l of links){const u=abs(l.href,item.url);if(!u||!allowed(u,source)||seen.has(u))continue;const hint=`${u} ${l.text}`;if(/\.pdf|torne|tournament|competition|draw|tabell|order|ordine|schedule|programma|accept|entry|player|profile|match|risultat/i.test(hint))queue.push({url:u,depth:item.depth+1})}}catch(e){errors.push(String(e.message||e).slice(0,160))}finally{await page.close()}}states.push({id:source.id,name:source.name,status:seen.size&&errors.length<seen.size?'active':'partial',pagesChecked:seen.size,errorCount:errors.length,lastRun:new Date().toISOString()})}
await browser.close();const nextMatches=[...matches.values()].sort((a,b)=>`${a.date}${a.time||''}`.localeCompare(`${b.date}${b.time||''}`)),nextEntries=[...entries.values()],oldMatch=new Map((old.matches||[]).map(m=>[m.key,`${m.date}|${m.time||''}|${m.court||''}|${m.opponent||''}`])),oldEntry=new Map((old.entryStatuses||[]).map(e=>[`${e.playerId}|${e.tournamentKey}`,`${e.status}|${e.position||''}`])),notifications=[];for(const m of nextMatches){const sig=`${m.date}|${m.time||''}|${m.court||''}|${m.opponent||''}`,prev=oldMatch.get(m.key);if(prev!==undefined&&prev!==sig)notifications.push({type:'match',playerName:m.playerName,message:`${m.tournamentName}: ${m.date} alle ${m.time||'orario da pubblicare'}${m.court?' · campo '+m.court:''}${m.opponent?' · contro '+m.opponent:''}`,url:m.url});else if(prev===undefined&&m.lastSeen)notifications.push({type:'match',playerName:m.playerName,message:`Nuova partita — ${m.tournamentName}, ${m.date} alle ${m.time||'orario da pubblicare'}`,url:m.url})}for(const e of nextEntries){const k=`${e.playerId}|${e.tournamentKey}`,sig=`${e.status}|${e.position||''}`;if(oldEntry.get(k)!==sig)notifications.push({type:'entry',playerName:e.playerName,message:`${e.tournamentName}: ${e.status}${e.position?' · posizione '+e.position:''}`,url:e.url})}
const data={...old,generatedAt:new Date().toISOString(),mode:'official-portals-vercel',players:players.map(p=>({id:p.id,name:p.name,club:p.club||null,circuits:p.circuits||[]})),tournaments:[...tournaments.values()],matches:nextMatches,entryStatuses:nextEntries,findings,sources:states};await fs.writeFile('data.json',JSON.stringify(data,null,2)+'\n');await fs.writeFile('alerts.json',JSON.stringify({generatedAt:data.generatedAt,notifications},null,2)+'\n');console.log(`Court Watch v5: ${seenSummary(states)}, ${findings.length} riscontri, ${notifications.length} avvisi.`);
function seenSummary(s){return s.map(x=>`${x.name} ${x.pagesChecked}`).join(', ')}
