import{chromium}from'playwright';import fs from'node:fs/promises';import path from'node:path';import os from'node:os';import{execFile}from'node:child_process';import{promisify}from'node:util';
const exec=promisify(execFile),ROOT='https:'+'//www.fitp.it',SEARCH=ROOT+'/Tornei/Ricerca-tornei',now=new Date().toISOString();
const data=JSON.parse(await fs.readFile('data.json','utf8')),old=new Map((data.matches||[]).map(m=>[m.key,`${m.date}|${m.time}|${m.court}|${m.opponent}`])),tmp=await fs.mkdtemp(path.join(os.tmpdir(),'puc-'));
const competitions=new Set(),pdfs=new Set(),docs=[],diag={startedAt:now,searchLoaded:false,cards:[],competitionUrls:[],pdfUrls:[],errors:[]};
const names=new Map((data.players||[]).map(p=>[p.id,[p.name,p.name.split(/\s+/).reverse().join(' ')].map(v=>v.toUpperCase())]));
function absolute(v,b=ROOT+'/'){try{return new URL(String(v).replace(/&amp;/g,'&'),b).href}catch{return null}}
function inspect(v,b){const s=String(v||'');for(const m of s.matchAll(/(?:https?:\/\/www\.fitp\.it)?\/(?:Tornei\/Dettaglio-Competizione|Pagine-Puc\/Competizione)\?competitionId=[A-Za-z0-9-]+/gi)){const u=absolute(m[0],b);if(u)competitions.add(u)}for(const m of s.matchAll(/(?:https?:\/\/[^\s"'<>]+|\/[^\s"'<>]+)\.pdf(?:\?[^\s"'<>]*)?/gi)){const u=absolute(m[0],b);if(u)pdfs.add(u)}}
async function pdfText(file){try{const out=file+'.txt';await exec('pdftotext',['-layout',file,out]);return await fs.readFile(out,'utf8')}catch(e){diag.errors.push('PDF: '+e.message);return''}}
function watch(page){page.on('response',r=>{const t=r.headers()['content-type']||'';if(/json|text|javascript|html/i.test(t))r.text().then(x=>{if(x.length<8e6)inspect(x,r.url())}).catch(()=>{})})}
let browser;try{browser=await chromium.launch({headless:true});const ctx=await browser.newContext({locale:'it-IT',timezoneId:'Europe/Rome',acceptDownloads:true});const page=await ctx.newPage();watch(page);
await page.goto(SEARCH,{waitUntil:'domcontentloaded',timeout:60000});diag.searchLoaded=true;await page.waitForTimeout(3500);
for(const s of['#iubenda-cs-accept-btn','#iubenda-cs-reject-btn','button:has-text("Accetta")']){const b=page.locator(s).first();if(await b.count())await b.click({timeout:1000}).catch(()=>{})}
const input=page.locator('input[placeholder*="torneo" i],input[type="search"]').first();if(await input.count()){await input.fill('JUNIOR NEXT GEN BRALLO');await input.press('Enter').catch(()=>{})}await page.waitForTimeout(5500);
for(let pass=0;pass<25;pass++){const titles=page.locator('span.cc-title.cc-clamp-d-2.cc-clamp-t-2');let found=false;for(let i=0;i<await titles.count();i++){const title=await titles.nth(i).innerText().catch(()=>'');if(!/JUNIOR NEXT GEN|CENTRO ESTIVO|BRALLO/i.test(title))continue;found=true;diag.cards.push(title.trim());const h=await titles.nth(i).evaluate(el=>{let p=el;for(let n=0;n<10&&p;n++,p=p.parentElement)if(/competitionId|Dettagli/i.test(p.outerHTML||''))return p.outerHTML;return''}).catch(()=>'');inspect(h,page.url())}if(found)break;const more=page.locator('#btn-loadMore');if(!(await more.count())||!(await more.isVisible().catch(()=>false)))break;await more.click().catch(()=>{});await page.waitForTimeout(1200)}inspect(await page.content(),page.url());
for(const url of[...competitions].slice(0,12)){const p=await ctx.newPage();watch(p);try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForTimeout(6500);inspect(await p.content(),p.url());for(const href of await p.locator('a[href]').evaluateAll(a=>a.map(x=>x.href)).catch(()=>[]))if(/\.pdf|ordine|order|tabellone/i.test(href))pdfs.add(href);const links=p.getByText(/Scarica pdf/i);for(let i=0;i<await links.count();i++){const l=links.nth(i),href=await l.getAttribute('href').catch(()=>null);if(href){const u=absolute(href,p.url());if(u)pdfs.add(u);continue}const pending=p.waitForEvent('download',{timeout:4000}).catch(()=>null);await l.click({timeout:2500}).catch(()=>{});const d=await pending;if(d){const f=path.join(tmp,await d.suggestedFilename());await d.saveAs(f);docs.push({url,text:await pdfText(f)})}}}catch(e){diag.errors.push(url+': '+e.message)}await p.close()}
for(const url of[...pdfs].slice(0,50))try{const r=await fetch(url);if(!r.ok)continue;const f=path.join(tmp,Math.random().toString(36)+'.pdf');await fs.writeFile(f,Buffer.from(await r.arrayBuffer()));docs.push({url,text:await pdfText(f)})}catch(e){diag.errors.push(url+': '+e.message)}
}catch(e){diag.errors.push('Scanner: '+e.message)}finally{if(browser)await browser.close().catch(()=>{})}
const months={gennaio:'01',febbraio:'02',marzo:'03',aprile:'04',maggio:'05',giugno:'06',luglio:'07',agosto:'08',settembre:'09',ottobre:'10',novembre:'11',dicembre:'12'};
function dateOf(t){const m=t.match(/(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\s+(20\d{2})/i);return m?`${m[3]}-${months[m[2].toLowerCase()]}-${m[1].padStart(2,'0')}`:null}
function timeNear(lines,at){for(let r=0;r<=10;r++)for(const i of[at+r,at-r]){const m=lines[i]?.match(/\b([01]?\d|2[0-3])[:.]([0-5]\d)\b/);if(m)return`${m[1].padStart(2,'0')}:${m[2]}`}return null}
function courtNear(lines,at,pos){const h=lines.slice(Math.max(0,at-120),at+1).find(l=>(l.match(/CAMPO\s+\d+/g)||[]).length>=3);if(!h)return null;return[...h.matchAll(/CAMPO\s+(\d+)/g)].map(m=>({n:m[1],p:m.index||0})).sort((a,b)=>Math.abs(a.p-pos)-Math.abs(b.p-pos))[0]?.n||null}
const updates=[];for(const doc of docs){if(!/ordine di gioco|orario di gioco|CAMPO\s+\d+/i.test(doc.text))continue;const date=dateOf(doc.text),lines=doc.text.split(/\r?\n/),upper=lines.map(l=>l.toUpperCase());if(!date)continue;for(const[id,aliases]of names){let at=-1,pos=-1,used='';for(let i=0;i<upper.length&&at<0;i++)for(const a of aliases){const p=upper[i].indexOf(a);if(p>=0){at=i;pos=p;used=a;break}}if(at<0)continue;const time=timeNear(lines,at);if(!time)continue;let match=(data.matches||[]).find(m=>m.playerId===id&&m.date===date);if(!match){const t=(data.tournaments||[]).find(t=>t.playerId===id&&/BRALLO|JUNIOR NEXT GEN/i.test(t.name||''));if(!t)continue;match={key:`puc|${date}|${id}`,playerId:id,playerName:t.playerName,tournamentName:t.name,location:t.location,date,time:null,court:null,opponent:null,url:t.url,sourceId:'fitp-puc',status:'scheduled'};(data.matches||=[]).push(match)}const surname=used.split(/\s+/)[0].replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),q=doc.text.match(new RegExp(`${surname}\\s+incontra\\s+([^;\\n.]+)`,'i'))?.[1]?.trim();match.time=time;match.court=courtNear(lines,at,pos)||match.court;match.opponent=q||match.opponent;match.url=doc.url;match.sourceName='P.U.C. FITP';match.verifiedAt=now;updates.push(match)}}
diag.competitionUrls=[...competitions];diag.pdfUrls=[...pdfs];diag.documents=docs.length;diag.finishedAt=new Date().toISOString();data.generatedAt=now;data.pucDiagnostics=diag;await fs.writeFile('data.json',JSON.stringify(data,null,2)+'\n');
const unique=[...new Map(updates.map(m=>[m.key,m])).values()],notifications=unique.filter(m=>old.get(m.key)!==`${m.date}|${m.time}|${m.court}|${m.opponent}`).map(m=>({type:'match',playerName:m.playerName,message:`${m.tournamentName}: ${m.date} alle ${m.time}${m.court?' · campo '+m.court:''}${m.opponent?' · contro '+m.opponent:''}`,url:m.url}));await fs.writeFile('alerts.json',JSON.stringify({generatedAt:now,notifications},null,2)+'\n');console.log(JSON.stringify({competitions:competitions.size,pdfs:pdfs.size,documents:docs.length,updates:unique.length,diagnostics:diag},null,2));
