import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec=promisify(execFile),before=JSON.parse(await fs.readFile('data.json','utf8')),players=before.players||[],oldMatches=JSON.parse(JSON.stringify(before.matches||[])),tmp=await fs.mkdtemp(path.join(os.tmpdir(),'puc-'));
const aliases=new Map(players.map(p=>[p.id,[p.name.toUpperCase(),p.name.split(/\s+/).reverse().join(' ').toUpperCase()]]));
const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({locale:'it-IT',timezoneId:'Europe/Rome',userAgent:'Mozilla/5.0 (compatible; CourtWatchPUC/2.0)'}),page=await ctx.newPage(),documents=[],competitionUrls=new Set(),pdfUrls=new Set();
function addCompetition(value){for(const m of String(value||'').matchAll(/(?:Pagine-Puc\/Competizione|Tornei\/Dettaglio-Competizione)\?competitionId=([A-Za-z0-9-]+)/ig))competitionUrls.add('https://www.fitp.it/Pagine-Puc/Competizione?competitionId='+m[1])}
function addPdfs(value,base){for(const m of String(value||'').matchAll(/(?:https?:\/\/[^\s"'<>]+|\/[^\s"'<>]+)\.pdf(?:\?[^\s"'<>]*)?/ig)){try{pdfUrls.add(new URL(m[0],base).href)}catch{}}}
page.on('response',r=>{const ct=r.headers()['content-type']||'';if(/json|text\//i.test(ct))documents.push((async()=>{try{const text=await r.text();if(text.length<6000000){addCompetition(text);addPdfs(text,r.url());return{url:r.url(),title:'Risposta P.U.C.',text}}}catch{}return null})())});
const searchUrl='https:'+'//www.fitp.it/Tornei/Ricerca-tornei';await page.goto(searchUrl,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForTimeout(2500);for(const sel of ['#iubenda-cs-reject-btn','#iubenda-cs-accept-btn','button:has-text("Rifiuta")','button:has-text("Accetta")']){const b=page.locator(sel).first();if(await b.count())await b.click({timeout:1000}).catch(()=>{})}
const inputs=page.locator('input[type="search"],input[type="text"]');for(let i=0;i<await inputs.count();i++){const input=inputs.nth(i),ph=((await input.getAttribute('placeholder'))||'').toLowerCase();if(/torneo|circolo|provincia|cerca/.test(ph)){await input.fill('TORNEO JUNIOR NEXT GEN PRESSO CENTRO ESTIVO FITP BRALLO');await input.press('Enter').catch(()=>{});break}}
for(const label of ['Cerca','CERCA']){const b=page.getByRole('button',{name:label,exact:true}).first();if(await b.count())await b.click({timeout:1500}).catch(()=>{})}
await page.waitForTimeout(6500);let html=await page.content(),body=await page.locator('body').innerText().catch(()=>'');addCompetition(html);addPdfs(html,page.url());for(const a of await page.locator('a[href]').evaluateAll(ns=>ns.map(n=>n.href))){addCompetition(a);if(/\.pdf/i.test(a))pdfUrls.add(a)}documents.push(Promise.resolve({url:page.url(),title:await page.title(),text:body}));await Promise.allSettled(documents);
for(const url of [...competitionUrls].slice(0,12)){const p=await ctx.newPage(),responses=[];p.on('response',r=>{const ct=r.headers()['content-type']||'';if(/json|text\//i.test(ct))responses.push((async()=>{try{const text=await r.text();if(text.length<6000000){addPdfs(text,r.url());return{url:r.url(),title:'Dati competizione P.U.C.',text}}}catch{}return null})())});try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await p.waitForTimeout(5000);const pageHtml=await p.content(),pageText=await p.locator('body').innerText().catch(()=>'');addPdfs(pageHtml,url);for(const a of await p.locator('a[href]').evaluateAll(ns=>ns.map(n=>n.href)))if(/\.pdf|ordine|order/i.test(a))pdfUrls.add(a);documents.push(Promise.resolve({url,title:await p.title(),text:pageText}));await Promise.allSettled(responses);documents.push(...responses)}catch{}finally{await p.close()}}
for(const url of [...pdfUrls].slice(0,30)){try{const r=await fetch(url);if(!r.ok)continue;const pdf=path.join(tmp,'p'+pdfUrls.size+'-'+Math.random()+'.pdf'),txt=pdf+'.txt';await fs.writeFile(pdf,Buffer.from(await r.arrayBuffer()));await exec('pdftotext',['-layout',pdf,txt]);documents.push(Promise.resolve({url,title:'Ordine di gioco P.U.C.',text:await fs.readFile(txt,'utf8')}))}catch{}}
const resolved=(await Promise.allSettled(documents)).filter(x=>x.status==='fulfilled'&&x.value).map(x=>x.value),updates=[];
function dateIn(text){const m=text.match(/\b(\d{1,2})[\/.](\d{1,2})(?:[\/.](20\d{2}))?\b/);if(m)return`${m[3]||2026}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const months={gennaio:'01',febbraio:'02',marzo:'03',aprile:'04',maggio:'05',giugno:'06',luglio:'07',agosto:'08',settembre:'09',ottobre:'10',novembre:'11',dicembre:'12'};const n=text.toLowerCase().match(/\b(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)(?:\s+(20\d{2}))?/);return n?`${n[3]||2026}-${months[n[2]]}-${n[1].padStart(2,'0')}`:null}
for(const doc of resolved){if(!/ordine di gioco|order of play|programma|orari|campo|court/i.test(doc.title+' '+doc.text.slice(0,2500)))continue;const upper=doc.text.toUpperCase();for(const [playerId,names]of aliases){let at=-1;for(const name of names){at=upper.indexOf(name);if(at>=0)break}if(at<0)continue;const snippet=doc.text.slice(Math.max(0,at-700),at+900),time=snippet.match(/\b(?:ore|non prima delle|not before|starting at)?\s*([01]?\d|2[0-3])[:.]([0-5]\d)\b/i);if(!time)continue;const existing=(before.matches||[]).find(m=>m.playerId===playerId&&!m.time),date=dateIn(snippet)||existing?.date;if(!existing||!date)continue;existing.time=`${time[1].padStart(2,'0')}:${time[2]}`;existing.court=snippet.match(/(?:campo|court)\s*(?:n\.?\s*)?([A-Za-z0-9-]+)/i)?.[1]||existing.court||null;existing.opponent=snippet.match(/(?:vs\.?|contro)\s+([A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ' -]{3,50})/i)?.[1]?.trim()||existing.opponent||null;existing.url=doc.url;existing.sourceName='P.U.C. FITP';existing.verifiedAt=new Date().toISOString();updates.push(existing)}}
await browser.close();before.generatedAt=new Date().toISOString();before.pucCompetitionUrls=[...competitionUrls];before.pucOrderUrls=[...pdfUrls];await fs.writeFile('data.json',JSON.stringify(before,null,2)+'\n');const old=new Map(oldMatches.map(m=>[m.key,`${m.time||''}|${m.court||''}|${m.opponent||''}`])),notifications=updates.filter(m=>old.get(m.key)!==`${m.time||''}|${m.court||''}|${m.opponent||''}`).map(m=>({type:'match',playerName:m.playerName,message:`${m.tournamentName}: ${m.date} alle ${m.time}${m.court?' · campo '+m.court:''}${m.opponent?' · contro '+m.opponent:''}`,url:m.url}));let alerts={generatedAt:before.generatedAt,notifications:[]};try{alerts=JSON.parse(await fs.readFile('alerts.json','utf8'))}catch{}alerts.generatedAt=before.generatedAt;alerts.notifications=[...(alerts.notifications||[]),...notifications];await fs.writeFile('alerts.json',JSON.stringify(alerts,null,2)+'\n');console.log(`PUC: ${competitionUrls.size} competizioni, ${pdfUrls.size} ordini, ${updates.length} orari aggiornati.`);
