import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec=promisify(execFile),data=JSON.parse(await fs.readFile('data.json','utf8')),oldMatches=JSON.parse(JSON.stringify(data.matches||[])),tmp=await fs.mkdtemp(path.join(os.tmpdir(),'puc-')),now=new Date().toISOString();
const names=new Map((data.players||[]).map(p=>[p.id,[p.name,p.name.split(/\s+/).reverse().join(' ')].map(x=>x.toUpperCase())]));
const diagnostics={startedAt:now,searchLoaded:false,matchingCards:[],competitionUrls:[],orderUrls:[],errors:[]},competitionUrls=new Set(),orderUrls=new Set(),documents=[];
function absolute(v,base='https://www.fitp.it/'){try{return new URL(v.replace(/&amp;/g,'&'),base).href}catch{return null}}
function inspect(value,base){const s=String(value||'');for(const m of s.matchAll(/(?:https?:\/\/www\.fitp\.it)?\/(?:Tornei\/Dettaglio-Competizione|Pagine-Puc\/Competizione)\?competitionId=([A-Za-z0-9-]+)/ig)){const u=absolute(m[0],base);if(u)competitionUrls.add(u)}for(const m of s.matchAll(/(?:https?:\/\/[^\s"'<>]+|\/[^\s"'<>]+)\.(?:pdf|PDF)(?:\?[^\s"'<>]*)?/g)){const u=absolute(m[0],base);if(u)orderUrls.add(u)}}
let browser;
try{
 browser=await chromium.launch({headless:true});const ctx=await browser.newContext({locale:'it-IT',timezoneId:'Europe/Rome',acceptDownloads:true,userAgent:'Mozilla/5.0 (compatible; CourtWatchOfficialPUC/3.0)'});const page=await ctx.newPage();
 const responseTasks=[];page.on('response',r=>{const ct=r.headers()['content-type']||'';if(/json|text|javascript/i.test(ct))responseTasks.push((async()=>{try{const text=await r.text();if(text.length<8000000){inspect(text,r.url());documents.push({url:r.url(),title:'Risposta P.U.C.',text})}}catch{}})())});
 try{await page.goto('https://www.fitp.it/Tornei/Ricerca-tornei',{waitUntil:'domcontentloaded',timeout:60000});diagnostics.searchLoaded=true}catch(e){diagnostics.errors.push('Apertura ricerca: '+e.message)}
 await page.waitForTimeout(4000);for(const sel of ['#iubenda-cs-accept-btn','#iubenda-cs-reject-btn','button:has-text("Accetta")','button:has-text("Rifiuta")']){const b=page.locator(sel).first();if(await b.count())await b.click({timeout:1200}).catch(()=>{})}
 const input=page.locator('input[placeholder*="torneo" i],input[placeholder*="circolo" i],input[type="search"]').first();if(await input.count()){await input.fill('JUNIOR NEXT GEN BRALLO');await input.press('Enter').catch(()=>{});const parent=input.locator('xpath=..');const localButton=parent.locator('button').first();if(await localButton.count())await localButton.click({timeout:1500}).catch(()=>{});else{const searchButton=page.getByRole('button',{name:/^cerca$/i}).first();if(await searchButton.count())await searchButton.click({timeout:1500}).catch(()=>{})}}
 await page.waitForTimeout(7000);
 for(let i=0;i<25;i++){const titles=page.locator('span.cc-title.cc-clamp-d-2.cc-clamp-t-2');let found=false;for(let j=0;j<await titles.count();j++){const text=(await titles.nth(j).innerText().catch(()=>''));if(/JUNIOR NEXT GEN|CENTRO ESTIVO|BRALLO/i.test(text)){found=true;diagnostics.matchingCards.push(text);const html=await titles.nth(j).evaluate(el=>{let p=el;for(let k=0;k<8&&p;k++,p=p.parentElement){const h=p.outerHTML||'';if(/competitionId|Dettagli/i.test(h))return h}return el.parentElement?.outerHTML||''}).catch(()=>'');inspect(html,page.url())}}if(found)break;const more=page.locator('#btn-loadMore');if(!(await more.count())||!(await more.isVisible().catch(()=>false)))break;await more.click().catch(()=>{});await page.waitForTimeout(1200)}
 const html=await page.content(),text=await page.locator('body').innerText().catch(()=>'');inspect(html,page.url());documents.push({url:page.url(),title:await page.title(),text});await Promise.allSettled(responseTasks);
 if(!competitionUrls.size&&diagnostics.matchingCards.length){const title=page.locator('span.cc-title.cc-clamp-d-2.cc-clamp-t-2').filter({hasText:/JUNIOR NEXT GEN|CENTRO ESTIVO|BRALLO/i}).first();const card=title.locator('xpath=ancestor::*[.//*[contains(normalize-space(.),"Dettagli")]][1]');const details=card.getByText(/Dettagli/i).last();if(await details.count()){await details.click().catch(()=>{});await page.waitForTimeout(5000);inspect(page.url(),page.url());inspect(await page.content(),page.url())}}
 for(const competitionUrl of [...competitionUrls].slice(0,10)){const p=await ctx.newPage(),tasks=[];p.on('response',r=>{const ct=r.headers()['content-type']||'';if(/json|text|javascript/i.test(ct))tasks.push((async()=>{try{const t=await r.text();if(t.length<8000000){inspect(t,r.url());documents.push({url:r.url(),title:'Dati competizione P.U.C.',text:t})}}catch{}})())});try{await p.goto(competitionUrl,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForTimeout(8000);const h=await p.content(),t=await p.locator('body').innerText().catch(()=>'');inspect(h,p.url());for(const href of await p.locator('a[href]').evaluateAll(as=>as.map(a=>a.href)))if(/pdf|ordine|order|tabellone/i.test(href))orderUrls.add(href);const downloads=p.getByText(/Scarica pdf/i);for(let i=0;i<await downloads.count();i++){const el=downloads.nth(i),href=await el.getAttribute('href').catch(()=>null);if(href){const u=absolute(href,p.url());if(u)orderUrls.add(u)}else{const dl=await Promise.race([p.waitForEvent('download',{timeout:2500}).catch(()=>null),el.click({timeout:2000}).then(()=>null).catch(()=>null)]);if(dl){const save=path.join(tmp,await dl.suggestedFilename());await dl.saveAs(save);documents.push({url:competitionUrl,title:'Ordine di gioco P.U.C.',text:await pdfText(save)})}}documents.push({url:p.url(),title:await p.title(),text:t});await Promise.allSettled(tasks)}catch(e){diagnostics.errors.push(competitionUrl+': '+e.message)}finally{await p.close()}}
 for(const url of [...orderUrls].slice(0,40)){try{const r=await fetch(url);if(!r.ok)continue;const file=path.join(tmp,'ordine-'+Math.random()+'.pdf');await fs.writeFile(file,Buffer.from(await r.arrayBuffer()));documents.push({url,title:'Ordine di gioco P.U.C.',text:await pdfText(file)})}catch(e){diagnostics.errors.push('PDF '+url+': '+e.message)}}
 diagnostics.competitionUrls=[...competitionUrls];diagnostics.orderUrls=[...orderUrls];
}catch(e){diagnostics.errors.push('Scanner: '+e.message)}finally{if(browser)await browser.close().catch(()=>{})}
async function pdfText(file){try{const out=file+'.txt';await exec('pdftotext',['-layout',file,out]);return await fs.readFile(out,'utf8')}catch{return''}}
function extractTime(text,at){const before=text.slice(Math.max(0,at-500),at),after=text.slice(at,at+700),patterns=[/\b(?:ore|non prima delle|not before|starting at)\s*([01]?\d|2[0-3])[:.]([0-5]\d)\b/i,/\b([01]?\d|2[0-3])[:.]([0-5]\d)\b/];for(const area of [before.split('\n').slice(-5).join('\n'),after.split('\n').slice(0,7).join('\n')])for(const re of patterns){const m=area.match(re);if(m)return`${m[1].padStart(2,'0')}:${m[2]}`}return null}
const updates=[];for(const doc of documents){const head=(doc.title+' '+doc.text.slice(0,3000));if(!/ordine di gioco|order of play|programma|orari|campo|court|BRALLO/i.test(head))continue;const upper=doc.text.toUpperCase();for(const [id,variants]of names){let at=-1;for(const n of variants){at=upper.indexOf(n);if(at>=0)break}if(at<0)continue;const time=extractTime(doc.text,at),match=(data.matches||[]).find(m=>m.playerId===id&&!m.time);if(!time||!match)continue;const context=doc.text.slice(Math.max(0,at-500),at+700);match.time=time;match.court=context.match(/(?:campo|court)\s*(?:n\.?\s*)?([A-Za-z0-9-]+)/i)?.[1]||match.court||null;match.opponent=context.match(/(?:vs\.?|contro)\s+([A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ' -]{3,50})/i)?.[1]?.trim()||match.opponent||null;match.url=doc.url;match.sourceName='P.U.C. FITP';match.verifiedAt=now;updates.push(match)}}
data.generatedAt=now;data.pucDiagnostics=diagnostics;await fs.writeFile('data.json',JSON.stringify(data,null,2)+'\n');const old=new Map(oldMatches.map(m=>[m.key,`${m.time||''}|${m.court||''}|${m.opponent||''}`])),fresh=[...new Map(updates.map(m=>[m.key,m])).values()].filter(m=>old.get(m.key)!==`${m.time||''}|${m.court||''}|${m.opponent||''}`).map(m=>({type:'match',playerName:m.playerName,message:`${m.tournamentName}: ${m.date} alle ${m.time}${m.court?' · campo '+m.court:''}${m.opponent?' · contro '+m.opponent:''}`,url:m.url}));let alerts={generatedAt:now,notifications:[]};try{alerts=JSON.parse(await fs.readFile('alerts.json','utf8'))}catch{}alerts.generatedAt=now;alerts.notifications=fresh;await fs.writeFile('alerts.json',JSON.stringify(alerts,null,2)+'\n');console.log(JSON.stringify({competitions:competitionUrls.size,orders:orderUrls.size,updates:fresh.length,diagnostics},null,2));
