import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const API='https://dp-myfit-test-function-v2.azurewebsites.net/api/v3/tornei/puc/list',ROOT='https://www.fitp.it',OUT=path.resolve('puc-inbox');
const data=JSON.parse(await fs.readFile('data.json','utf8')),players=JSON.parse(await fs.readFile('players.json','utf8')).players||[];
const diagnostics={startedAt:new Date().toISOString(),api:API,queries:[],competitions:[],detailPages:[],candidateDocuments:[],savedDocuments:[],errors:[]};await fs.mkdir(OUT,{recursive:true});
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim(),aliases=players.flatMap(p=>[p.name,...(p.aliases||[])]).map(normalize),tracked=(data.tournaments||[]).filter(t=>t.sourceId==='fitp-puc'&&t.status!=='finished');
const anchors=[...new Set(tracked.flatMap(t=>{const n=normalize(`${t.name} ${t.location}`);if(n.includes('BRALLO'))return['BRALLO'];const l=normalize(t.location).replace(/\b[A-Z]{2}\b/g,'').trim();return[l,normalize(t.name)].filter(v=>v.length>=4)}))].slice(0,30);
const payload=q=>({guid:'',profilazione:'',freetext:q,id_regione:'',id_provincia:'',id_stato:'',id_disciplina:'',sesso:'',data_inizio:'',data_fine:'',tipo_competizione:'',categoria_eta:'',id_classifica:'',classifica:'',massimale_montepremi:'',id_area_regionale:'',ambito:'',rowstoskip:0,fetchrows:100,sortcolumn:'',sortorder:''}),relevant=c=>{const text=normalize(`${c.nome_torneo} ${c.citta} ${c.provincia}`);if(text.includes('BRALLO'))return true;return tracked.some(t=>normalize(`${t.name} ${t.location}`).split(' ').filter(w=>w.length>=5).filter(w=>text.includes(w)).length>=2)},absolute=(v,b=ROOT+'/')=>{try{return new URL(String(v).replace(/&amp;/g,'&'),b).href}catch{return null}};
const candidates=new Set();function inspect(body,base,label=''){const text=String(body||'');for(const m of text.matchAll(/(?:https?:\/\/[^\s"'<>]+|\/[^\s"'<>]+)\.pdf(?:\?[^\s"'<>]*)?/gi)){const url=absolute(m[0],base),around=text.slice(Math.max(0,m.index-500),Math.min(text.length,m.index+m[0].length+500));if(url&&(/ordine|orario|gioco|programma/i.test(`${url} ${label} ${around}`)||aliases.some(a=>normalize(around).includes(a))))candidates.add(url)}}async function savePdf(url,bytes,hint=''){if(!bytes?.length||bytes.slice(0,4).toString()!=='%PDF')return;const name=`${crypto.createHash('sha1').update(bytes).digest('hex').slice(0,12)}-ordine-di-gioco.pdf`;await fs.writeFile(path.join(OUT,name),bytes);diagnostics.savedDocuments.push({file:name,url,hint})}
for(const query of anchors)try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0 CourtWatch/1.0',origin:ROOT,referer:ROOT+'/'},body:JSON.stringify(payload(query))}),text=await r.text();let body;try{body=JSON.parse(text)}catch{body={}}const list=(body.competizioni||[]).filter(relevant);diagnostics.queries.push({query,status:r.status,record:body.record||0,matched:list.length});diagnostics.competitions.push(...list)}catch(error){diagnostics.errors.push(`${query}: ${error.message}`)}
diagnostics.competitions=[...new Map(diagnostics.competitions.map(c=>[c.guid||c.id_torneo_digital,c])).values()];let browser;try{browser=await chromium.launch({headless:true});const context=await browser.newContext({locale:'it-IT',timezoneId:'Europe/Rome',acceptDownloads:true});for(const c of diagnostics.competitions.filter(c=>Number(c.cod_fonte)===1)){if(Number(c.id_statoPUC)!==2&&!normalize(c.nome_torneo).includes('BRALLO'))continue;const url=`${ROOT}/Tornei/Dettaglio-Competizione?competitionId=${c.guid}`,page=await context.newPage(),detail={name:c.nome_torneo,guid:c.guid,url,network:[],api:[],links:[]},tasks=[];page.on('response',response=>{const u=response.url(),type=response.headers()['content-type']||'';if(/fitp|federtennis|azure|blob/i.test(u))detail.network.push(u);if(/\/api\/v3\/puc\/competizione\//i.test(u))tasks.push(response.text().then(body=>{detail.api.push({url:u,status:response.status(),requestBody:response.request().postData(),responseBody:body.slice(0,50000)});inspect(body,u)}).catch(()=>{}));else if(/json|html|text|javascript/i.test(type))tasks.push(response.text().then(body=>inspect(body,u)).catch(()=>{}));if(/application\/pdf/i.test(type))candidates.add(u)});try{await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(8000);const links=await page.locator('a[href]').evaluateAll(nodes=>nodes.map(a=>({href:a.href,text:(a.textContent||'').trim()})));detail.links=links.filter(l=>/pdf|ordine|orario|gioco|programma|tabellone/i.test(`${l.href} ${l.text}`));for(const l of detail.links)inspect(l.href,page.url(),l.text);await Promise.allSettled(tasks)}catch(error){diagnostics.errors.push(`${url}: ${error.message}`)}detail.network=[...new Set(detail.network)].slice(0,500);diagnostics.detailPages.push(detail);await page.close()}for(const url of [...candidates].slice(0,80))try{const r=await context.request.get(url,{timeout:45000});if(r.ok())await savePdf(url,Buffer.from(await r.body()))}catch(error){diagnostics.errors.push(`${url}: ${error.message}`)}}catch(error){diagnostics.errors.push(`Browser: ${error.stack||error.message}`)}finally{if(browser)await browser.close().catch(()=>{})}
diagnostics.candidateDocuments=[...candidates];diagnostics.finishedAt=new Date().toISOString();await fs.writeFile('puc-discovery.json',JSON.stringify(diagnostics,null,2)+'\n');await fs.writeFile('puc-api.json',JSON.stringify(diagnostics.detailPages.map(d=>({name:d.name,guid:d.guid,api:d.api})),null,2)+'\n');console.log(JSON.stringify({queries:diagnostics.queries,competitions:diagnostics.competitions.length,detailPages:diagnostics.detailPages.length,candidates:candidates.size,saved:diagnostics.savedDocuments.length,errors:diagnostics.errors.length},null,2));
