import fs from 'node:fs/promises';
import path from 'node:path';
const BASE='https://dp-myfit-test-function-v2.azurewebsites.net',SEARCH=`${BASE}/api/v3/tornei/puc/list`,OUT=path.resolve('puc-inbox');
const data=JSON.parse(await fs.readFile('data.json','utf8')),players=JSON.parse(await fs.readFile('players.json','utf8')).players||[],report={startedAt:new Date().toISOString(),searchEndpoint:SEARCH,queries:[],competitions:[],downloads:[],errors:[]};await fs.mkdir(OUT,{recursive:true});
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim(),tracked=(data.tournaments||[]).filter(t=>t.sourceId==='fitp-puc'&&t.status!=='finished'),anchors=[...new Set(tracked.flatMap(t=>{const all=normalize(`${t.name} ${t.location}`);if(all.includes('BRALLO'))return['BRALLO'];const location=normalize(t.location).replace(/\b[A-Z]{2}\b/g,'').trim();return[location,normalize(t.name)].filter(v=>v.length>=4)}))].slice(0,40),searchPayload=freetext=>({guid:'',profilazione:'',freetext,id_regione:'',id_provincia:'',id_stato:'',id_disciplina:'',sesso:'',data_inizio:'',data_fine:'',tipo_competizione:'',categoria_eta:'',id_classifica:'',classifica:'',massimale_montepremi:'',id_area_regionale:'',ambito:'',rowstoskip:0,fetchrows:100,sortcolumn:'',sortorder:''}),relevant=c=>{const text=normalize(`${c.nome_torneo} ${c.citta} ${c.provincia}`);if(text.includes('BRALLO'))return true;return tracked.some(t=>normalize(`${t.name} ${t.location}`).split(' ').filter(w=>w.length>=5).filter(w=>text.includes(w)).length>=2)};
async function jsonPost(url,body){const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0 CourtWatch/1.0',origin:'https://www.fitp.it',referer:'https://www.fitp.it/'},body:JSON.stringify(body)}),text=await response.text();if(!response.ok)throw new Error(`${response.status} ${text.slice(0,300)}`);return text?JSON.parse(text):null}
for(const query of anchors)try{const body=await jsonPost(SEARCH,searchPayload(query)),matches=(body?.competizioni||[]).filter(relevant);report.queries.push({query,record:body?.record||0,matched:matches.length});report.competitions.push(...matches)}catch(error){report.errors.push(`Search ${query}: ${error.message}`)}report.competitions=[...new Map(report.competitions.map(c=>[c.guid||c.id_torneo_digital,c])).values()];
for(const competition of report.competitions.filter(c=>Number(c.cod_fonte)===1))try{const detail=await jsonPost(`${BASE}/api/v3/puc/competizione/dettaglio`,{competitionUid:competition.guid});competition.officialId=detail?.CompetitionId||null;competition.monitoredParticipants=[];for(const tournament of detail?.Tournaments||[])for(const participant of tournament.Participants||[]){const full=normalize(`${participant.Name} ${participant.Surname}`),player=players.find(p=>normalize(p.name)===full||(p.aliases||[]).some(a=>normalize(a)===full));if(player&&!competition.monitoredParticipants.some(x=>x.playerId===player.id&&x.tournament===tournament.TournamentDescription))competition.monitoredParticipants.push({playerId:player.id,playerName:player.name,tournament:tournament.TournamentDescription,membershipCard:participant.MembershipCard,ranking:participant.Ranking})}const files=await jsonPost(`${BASE}/api/v3/puc/competizione/ordine-di-gioco/list`,{competitionId:competition.guid});competition.orderOfPlayFiles=Array.isArray(files)?files:[];for(const fileName of competition.orderOfPlayFiles){const url=`${BASE}/api/v2/puc/competizione/ordine-di-gioco/download?competitionId=${encodeURIComponent(competition.guid)}&fileName=${encodeURIComponent(fileName)}`;try{const response=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 CourtWatch/1.0'}}),bytes=Buffer.from(await response.arrayBuffer()),isPdf=bytes.subarray(0,4).toString()==='%PDF';if(!response.ok||!isPdf)throw new Error(`${response.status} ${response.headers.get('content-type')||''}`);const safe=`${competition.guid.slice(0,8)}-${path.basename(fileName).replace(/[^a-zA-Z0-9._-]+/g,'-')}`;await fs.writeFile(path.join(OUT,safe),bytes);report.downloads.push({competition:competition.nome_torneo,fileName,savedAs:safe,url,bytes:bytes.length})}catch(error){report.errors.push(`Download ${competition.nome_torneo}/${fileName}: ${error.message}`)}}}catch(error){report.errors.push(`Competition ${competition.nome_torneo}: ${error.message}`)}
report.finishedAt=new Date().toISOString();await fs.writeFile('puc-discovery.json',JSON.stringify(report,null,2)+'\n');await fs.writeFile('puc-api.json',JSON.stringify({competitions:report.competitions.map(c=>({guid:c.guid,name:c.nome_torneo,officialId:c.officialId,orderOfPlayFiles:c.orderOfPlayFiles,monitoredParticipants:c.monitoredParticipants})),downloads:report.downloads,errors:report.errors},null,2)+'\n');console.log(JSON.stringify({queries:report.queries,competitions:report.competitions.length,downloads:report.downloads.length,errors:report.errors},null,2));
