import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const API='https://dp-myfit-test-function-v2.azurewebsites.net/api/v3/tornei/puc/list',ROOT='https://www.fitp.it',OUT=path.resolve('puc-inbox');
const data=JSON.parse(await fs.readFile('data.json','utf8')),players=JSON.parse(await fs.readFile('players.json','utf8')).players||[];
const diagnostics={startedAt:new Date().toISOString(),api:API,queries:[],competitions:[],detailPages:[],candidateDocuments:[],savedDocuments:[],errors:[]};await fs.mkdir(OUT,{recursive:true});
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
const aliases=players.flatMap(p=>[p.name,...(p.aliases||[])]).map(normalize),tracked=(data.tournaments||[]).filter(t=>t.sourceId==='fitp-puc'&&t.status!=='finished');
const anchors=[...new Set(tracked.flatMap(t=>{const n=normalize(`${t.name} ${t.location}`);if(n.includes('BRALLO'))return['BRALLO'];const l=normalize(t.location).replace(/\b[A-Z]{2}\b/g,'').trim();return[l,normalize(t.name)].filter(v=>v.length>=4);} ))].slice(0,30);
const payload=q=>({guid:'',profilazione:'',freetext:q,id_regione:'',id_provincia:'',id_stato:'',id_disciplina:'',sesso:'',data_inizio:'',data_fine:'',tipo_competizione:'',categoria_eta:'',id_classifica:'',classifica:'',massimale_montepremi:'',id_area_regionale:'',ambito:'',rowstoskip:0,fetchrows:100,sortcolumn:'',sortorder:''});
const relevant=c=>{const text=normalize(`${c.nome_torneo} ${c.citta} ${c.provincia}`);if(text.includes('BRALLO'))return true;return tracked.some(t=>normalize(`${t.name} ${t.location}`).split(' ').filter(w=>w.length>=5).filter(w=>text.includes(w)).length>=2);};
const absolute=(value,base=ROOT+'/')=>{try{return new URL(String(value).replace(/&amp;/g,'&'),base).href}catch{return null}};
const candidateUrls=new Set();function inspect(body,base,label=''){const text=String(body||'');for(const match of text.matchAll(/(?:https?:\/\/[^\s"'<>]+|\/[^\s"'<>]+)\.pdf(?:\?[^\s"'<>]*)?/gi)){const url=absolute(match[0],base),around=text.slice(Math.max(0,match.index-500),Math.min(text.length,match.index+match[0].length+500));if(url&&(/ordine|orario|gioco|programma/i.test(`${url} ${label} ${around}`)||aliases.some(a=>normalize(around).includes(a))))candidateUrls.add(url);}}
async function savePdf(url,bytes,hint=''){if(!bytes?.length||bytes.slice(0,4).toString()!=='%PDF')return null;const name=`${crypto.createHash('sha1').update(bytes).digest('hex').slice(0,12)}-ordine-di-gioco.pdf`;await fs.writeFile(path.join(OUT,name),bytes);diagnostics.savedDocuments.push({file:name,url,hint});return name;}
for(const query of anchors){try{const response=await fetch(API,{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0 CourtWatch/1.0',origin:ROOT,referer:ROOT+'/'},body:JSON.stringify(payload(query))}),text=await response.text();let body;try{body=JSON.parse(text)}catch{body={}}const competitions=(body.competizioni||[]).filter(relevant);diagnostics.queries.push({query,status:response.status,record:body.record||0,matched:competitions.length});diagnostics.competitions.push(...competitions);}catch(error){diagnostics.errors.push(`${query}: ${error.message}`)}}
diagnostics.competitions=[...new Map(diagnostics.competitions.map(c=>[c.guid||c.id_torneo_digital,c])).values()];
let browser;try{browser=await chromium.launch({headless:true});const context=await browser.newContext({locale:'it-IT',timezoneId:'Europe/Rome',acceptDownloads:true});for(const competition of diagnostics.competitions.filter(c=>Number(c.cod_fonte)===1)){const url=`${ROOT}/Tornei/Dettaglio-Competizione?competitionId=${competition.guid}`,page=await context.newPage(),detail={name:competition.nome_torneo,guid:competition.guid,url,network:[],links:[],texts:[]},responseTasks=[];page.on('response',response=>{const u=response.url();if(/fitp|federtennis|azure|blob/i.test(u))detail.network.push(u);const type=response.headers()['content-type']||'';if(/json|html|text|javascript/i.test(type))responseTasks.push(response.text().then(body=>inspect(body,u)).catch(()=>{}));if(/application\/pdf/i.test(type))candidateUrls.add(u)});try{await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(8000);for(const selector of ['#iubenda-cs-accept-btn','#iubenda-cs-reject-btn']){const button=page.locator(selector).first();if(await button.count())await button.click({timeout:1000}).catch(()=>{})}const links=await page.locator('a[href]').evaluateAll(nodes=>nodes.map(a=>({href:a.href,text:(a.textContent||'').trim()})));detail.links=links.filter(l=>/pdf|ordine|orario|gioco|programma|tabellone/i.test(`${l.href} ${l.text}`));for(const link of detail.links)inspect(link.href,page.url(),link.text);const actions=page.getByText(/ordine di gioco|orario di gioco|programma|scarica.*pdf/i);for(let i=0;i<await actions.count();i++){const action=actions.nth(i);detail.texts.push((await action.innerText().catch(()=>'' )).trim());const href=await action.getAttribute('href').catch(()=>null);if(href)inspect(href,page.url(),detail.texts.at(-1));const pending=page.waitForEvent('download',{timeout:4000}).catch(()=>null);await action.click({timeout:2000}).catch(()=>{});const download=await pending;if(download){const stream=await download.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);await savePdf(page.url(),Buffer.concat(chunks),detail.texts.at(-1));}}await Promise.allSettled(responseTasks);inspect(await page.content(),page.url());}catch(error){diagnostics.errors.push(`${url}: ${error.message}`)}detail.network=[...new Set(detail.network)].slice(0,500);diagnostics.detailPages.push(detail);await page.close()}for(const url of [...candidateUrls].slice(0,80)){try{const response=await context.request.get(url,{timeout:45000});if(response.ok())await savePdf(url,Buffer.from(await response.body()))}catch(error){diagnostics.errors.push(`${url}: ${error.message}`)}}}catch(error){diagnostics.errors.push(`Browser: ${error.stack||error.message}`)}finally{if(browser)await browser.close().catch(()=>{})}
diagnostics.candidateDocuments=[...candidateUrls];diagnostics.finishedAt=new Date().toISOString();await fs.writeFile('puc-discovery.json',JSON.stringify(diagnostics,null,2)+'\n');console.log(JSON.stringify({queries:diagnostics.queries,competitions:diagnostics.competitions.length,detailPages:diagnostics.detailPages.length,candidates:candidateUrls.size,saved:diagnostics.savedDocuments.length,errors:diagnostics.errors.length},null,2));
