const SOURCE='https://raw.githubusercontent.com/png8nftp9y-alt/png8nftp9y-alt.github.io/main/dist/data-preview.json';
const PLAYER='virginia-cereghini';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const circuit=x=>{const s=String(x.source||x.sourceId||x.sourceName||'').toLowerCase();return s.includes('tennis')?'tennis-europe':s.includes('itf')?'itf':'fitp'};
const fmt=d=>{try{return new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00'))}catch{return d||''}};
function isDouble(m){return String(m.eventType||m.draw||m.category||'').toLowerCase().includes('double')||String(m.eventType||m.draw||m.category||'').toLowerCase().includes('doppio')||String(m.partner||'').includes('/');}
function row(m){const done=!!m.result||m.status==='completed';const badge=m.advances===false?'loss':m.advances===true?'win':'';return `<div class="row"><div class="time">${esc(m.time||'—')}</div><div><div class="title">${esc(m.playerName)} · ${isDouble(m)?'Doppio':'Singolare'} <span class="source ${circuit(m)}">${circuit(m)==='tennis-europe'?'TE':circuit(m).toUpperCase()}</span></div><div class="meta">${esc(m.tournamentName||m.name||'')} ${m.date?'· '+fmt(m.date):''}</div><div class="meta">${m.partner&&m.partner!==m.playerName?'con '+esc(m.partner)+' · ':''}vs ${esc(m.opponent||'Avversario da definire')}${m.opponentRanking?' · classifica '+esc(m.opponentRanking):''}${m.court?' · campo '+esc(m.court):''}</div>${m.result?`<div class="meta">Risultato: ${esc(m.result)}</div>`:''}</div><div class="badge ${badge}">${done?'Storico':'Agenda'}</div></div>`}
function tour(t){return `<div class="row"><div class="time">${esc((t.startDate||'').slice(5)||'—')}</div><div><div class="title">${esc(t.name)} <span class="source ${circuit(t)}">${circuit(t)==='tennis-europe'?'TE':circuit(t).toUpperCase()}</span></div><div class="meta">${esc(t.location||'Luogo da pubblicare')} · ${fmt(t.startDate)} – ${fmt(t.endDate)} · ${esc(t.status||'')}</div></div><div class="badge">Torneo</div></div>`}
async function load(){const res=await fetch(SOURCE+'?t='+Date.now(),{cache:'no-store'});const data=await res.json();const player=(data.players||[]).find(p=>p.id===PLAYER);const matches=(data.matches||[]).filter(m=>m.playerId===PLAYER).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'99:99').localeCompare(String(b.time||'99:99')));const agenda=matches.filter(m=>m.date&&!m.result&&m.status!=='completed').sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.time||'99:99').localeCompare(String(b.time||'99:99')));const tournaments=(data.tournaments||[]).filter(t=>t.playerId===PLAYER).sort((a,b)=>String(a.startDate||'').localeCompare(String(b.startDate||'')));$('subtitle').textContent=`${player?.ranking?'Classifica '+player.ranking+' · ':''}${player?.club||'Tesseramento da completare'} · dati v2 separati`;$('status').textContent='Aggiornato '+new Intl.DateTimeFormat('it-IT',{hour:'2-digit',minute:'2-digit'}).format(new Date(data.generatedAt||Date.now()));$('agenda').innerHTML=agenda.length?agenda.map(row).join(''):'<div class="empty">Nessuna partita futura in agenda.</div>';$('tournaments').innerHTML=tournaments.length?tournaments.map(tour).join(''):'<div class="empty">Nessun torneo.</div>';$('matches').innerHTML=matches.length?matches.map(row).join(''):'<div class="empty">Nessuna partita.</div>';}
load().catch(e=>{$('status').textContent='Errore dati';console.error(e)});setInterval(load,30000);
