const V3='https://raw.githubusercontent.com/png8nftp9y-alt/png8nftp9y-alt.github.io/main/dist/v3/';
const state={data:null,month:new Date(),agenda:new Date(),selected:new Set()};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const iso=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*6e4);return x.toISOString().slice(0,10)},add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},monday=d=>add(d,-((d.getDay()+6)%7)),initials=n=>String(n||'').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase(),fmt=d=>new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);
const circuit=x=>{const s=(x.sourceId||x.source||x.sourceName||x.circuit||'').toLowerCase();return s.includes('tennis-europe')||s.includes('tennis europe')||s==='te'?'tennis-europe':s.includes('itf')?'itf':'fitp'},active=t=>!['eliminated','excluded'].includes(t.status),overlap=(t,a,b)=>active(t)&&(!t.startDate||t.startDate<=b)&&(!t.endDate||t.endDate>=a);
const cityCountry=s=>{let v=String(s||'').replace(/^Tournaments\s+/i,'').trim();if(v.includes('|'))v=v.split('|').pop().trim();const m=v.match(/([A-Za-zÀ-ÿ' .-]+,\s*[A-Za-zÀ-ÿ' .-]+)(?:\s|$)/);return (m?m[1]:v).trim()||'Città/stato da pubblicare'};
async function v3json(path){const r=await fetch(V3+path+'?t='+Date.now(),{cache:'no-store',mode:'cors'});if(!r.ok)throw Error('File v3 mancante: '+path);return r.json()}
function matchMeta(m){const isDouble=m.matchType==='doubles'||m.eventType==='doubles'||/doppio|double/i.test(`${m.draw||''} ${m.category||''} ${m.eventType||''} ${m.partner||''}`),op=m.opponentOptions?.length?m.opponentOptions.join(' oppure '):m.opponent;return{isDouble,op,condition:m.condition||m.note||''}}
function opponentHtml(m,x){if(!x.op)return'Avversario da definire';const club=m.opponentClub?` · circolo ${esc(m.opponentClub)}`:'';const nat=m.opponentNationality?` · naz. ${esc(m.opponentNationality)}`:'';const ranking=m.opponentRanking?` · classifica ${esc(m.opponentRanking)}`:'';return`vs <span class="opponentName">${esc(x.op)}</span>${ranking}<span class="opponentClub">${club}${nat}</span>`}
function mergeAgenda(agenda,matches){const byId=new Map(matches.map(m=>[m.id,m]));return agenda.map(a=>({...byId.get(a.matchId),...a}))}
function renderFilters(){const ps=state.data.players||[];$('playerFilters').innerHTML=ps.map(p=>`<button class="chip ${state.selected.has(p.id)?'selected':''}" data-filter="${esc(p.id)}">${esc(p.name)}</button>`).join('');$('toggleAll').textContent=state.selected.size?'Deseleziona tutti':'Seleziona tutti';document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.selected.has(b.dataset.filter)?state.selected.delete(b.dataset.filter):state.selected.add(b.dataset.filter);renderHome()})}
function renderAgenda(){const key=iso(state.agenda),items=(state.data.agenda||[]).filter(m=>m.date===key&&state.selected.has(m.playerId)).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));$('agendaDate').textContent=fmt(state.agenda);$('dailyAgenda').innerHTML=items.length?`<div class="agendaList">${items.map(m=>{const x=matchMeta(m),loss=m.advances===false?' loss':'',win=m.advances===true?' win':'';return`<article class="agendaItem${loss}${win}" data-player="${esc(m.playerId)}"><time>${esc(m.time||'—')}</time><div><div class="agendaTitle"><strong>${esc(m.playerName)}</strong><span class="type ${x.isDouble?'double':''}">${x.isDouble?'Doppio':'Singolare'}</span><span class="type ${circuit(m)}">${circuit(m)==='itf'?'ITF':circuit(m)==='tennis-europe'?'Tennis Europe':'FITP'}</span></div><p>${esc(m.tournamentName)}${m.court?' · Campo '+esc(m.court):''}</p><p class="versus">${m.partner?'con '+esc(m.partner)+' · ':''}${opponentHtml(m,x)}</p>${x.condition?`<p class="condition">${esc(x.condition)}</p>`:''}${m.result?`<p class="result${loss}${win}">Risultato: ${esc(m.result)}</p>`:''}</div><span class="badge ${m.result?'finished':''}${loss?' loss':''}">${m.result?'Terminata':'Partita'}</span></article>`}).join('')}</div>`:'<div class="empty">Nessuna partita confermata per questa giornata.</div>';document.querySelectorAll('.agendaItem[data-player]').forEach(x=>x.onclick=()=>openProfile(x.dataset.player))}
function groups(){const map=new Map();for(const t of state.data.tournaments||[]){if(!state.selected.has(t.playerId)||!active(t))continue;const identity=t.competitionId||t.itfTournamentKey||t.teTournamentId||String(t.name).toUpperCase().replace(/[^A-Z0-9]+/g,'-'),key=`${identity}|${cityCountry(t.location)}|${circuit(t)}`,g=map.get(key)||{...t,location:cityCountry(t.location),players:[],playerIds:[]};if(!g.players.includes(t.playerName))g.players.push(t.playerName);if(!g.playerIds.includes(t.playerId))g.playerIds.push(t.playerId);map.set(key,g)}return[...map.values()]}
function renderCalendar(){const first=new Date(state.month.getFullYear(),state.month.getMonth(),1,12),last=new Date(state.month.getFullYear(),state.month.getMonth()+1,0,12),start=monday(first);$('monthTitle').textContent='Calendario tornei · '+new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(first);let html='<div class="weekdays">'+['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(x=>`<b>${x}</b>`).join('')+'</div>';const all=groups();for(let ws=new Date(start);ws<=last;ws=add(ws,7)){const we=add(ws,6),a=iso(ws),b=iso(we),bars=all.filter(t=>overlap(t,a,b));html+=`<section class="calWeek"><div class="dates">${[0,1,2,3,4,5,6].map(i=>{const d=add(ws,i),k=iso(d),inCurrent=d.getMonth()===first.getMonth();return`<span class="${inCurrent?'':'out'} ${k===iso(new Date())?'today':''}">${d.getDate()}</span>`}).join('')}</div><div class="bands">${bars.map(t=>{const rawS=Math.round((new Date((t.startDate||a)+'T12:00:00')-ws)/864e5),rawE=Math.round((new Date((t.endDate||b)+'T12:00:00')-ws)/864e5),s=Math.max(0,rawS),e=Math.min(6,rawE),loc=cityCountry(t.location),players=t.players.join(', ');if(e<0||s>6)return'';return`<button class="tourBand ${circuit(t)}" style="grid-column:${s+1}/${e+2}" data-player="${esc(t.playerIds[0])}" title="${esc(t.name+' · '+loc+' · '+players)}"><strong>${esc(t.name)}</strong><span>${esc(loc)} · ${esc(players)}</span></button>`}).join('')}</div></section>`} $('calendar').innerHTML=html;document.querySelectorAll('.tourBand[data-player]').forEach(x=>x.onclick=()=>openProfile(x.dataset.player))}
function renderPlayers(){const ps=state.data.players||[];$('playerTotal').textContent=ps.length;$('playersList').innerHTML=ps.map(p=>{const n=(state.data.tournaments||[]).filter(t=>t.playerId===p.id&&active(t)).length,club=p.club||'Tesseramento da completare',card=p.membershipCard?` · tessera ${p.membershipCard}`:'';return`<div class="playerRow" data-profile="${esc(p.id)}"><div class="avatar">${initials(p.name)}</div><div><strong>${esc(p.name)}</strong><small>${esc(club)}${esc(card)} · ${n?`${n} ${n===1?'torneo':'tornei'} monitorati`:'Ricerca iscrizioni in corso'}</small></div><i>›</i></div>`}).join('');document.querySelectorAll('[data-profile]').forEach(x=>x.onclick=()=>openProfile(x.dataset.profile))}
function statusEmoji(s){return s==='green'?'🟢':s==='red'?'🔴':'🟡'}
function renderDiagnostics(){const d=state.data,diag=d.diagnostics||{},items=diag.items||[];const overall=diag.overall||'yellow';$('motorLight').textContent=statusEmoji(overall);$('miniStatus').innerHTML=`<div class="diagSummary"><b>${statusEmoji(overall)} Motore V3</b><small>${overall==='green'?'tutto regolare':overall==='red'?'problema critico':'attenzione: alcune aree parziali'}</small></div><div class="diagList">${items.map(x=>`<div class="diagRow ${esc(x.status)}"><span>${statusEmoji(x.status)}</span><div><b>${esc(x.label)}</b><small>${esc(x.detail)}</small></div></div>`).join('')}</div><div class="diagFooter"><p><b>${d.tournamentEntries.length}</b> iscrizioni torneo · <b>${d.agenda.length}</b> agenda · <b>${d.results.length}</b> risultati</p></div>`}
function renderMini(){renderDiagnostics()}
function renderHome(){renderFilters();renderAgenda();renderCalendar();renderPlayers();renderMini()}
function openProfile(id){location.hash='player/'+encodeURIComponent(id)}
function renderProfile(id){const p=state.data.players.find(x=>x.id===id);if(!p){location.hash='';return}const ts=(state.data.tournaments||[]).filter(t=>t.playerId===id),ms=(state.data.matches||[]).filter(m=>m.playerId===id);$('profileContent').innerHTML=`<div class="card profileHero"><div class="avatar big">${initials(p.name)}</div><div><h2>${esc(p.name)}</h2><p>${esc(p.club||'Tesseramento da completare')}${p.membershipCard?' · tessera '+esc(p.membershipCard):''}${p.ranking?' · classifica '+esc(p.ranking):''}</p></div></div><div class="profileGrid"><div class="card"><div class="cardHead"><h3>Tornei iscrizione</h3><span>${ts.length}</span></div>${ts.length?ts.map(t=>`<div class="listItem"><h4><i class="sourceDot ${circuit(t)}"></i>${esc(t.name)}</h4><p>${esc(cityCountry(t.location))} · ${esc(t.startDate||'')} – ${esc(t.endDate||'')}</p><p>${esc(t.sourceName||'Fonte v3')} · ordine di gioco ${(!t.endDate||t.endDate>=iso(new Date()))?'da monitorare':'non attivo'}</p></div>`).join(''):'<div class="empty">Ricerca iscrizioni in corso.</div>'}</div><div class="card"><div class="cardHead"><h3>Agenda e risultati</h3><span>${ms.length}</span></div>${ms.length?ms.map(m=>{const x=matchMeta(m),loss=m.advances===false?' loss':'',win=m.advances===true?' win':'';return`<div class="listItem"><h4>${esc(m.date||'data da pubblicare')} · ${esc(m.time||'orario da pubblicare')} · ${x.isDouble?'Doppio':'Singolare'}</h4><p>${opponentHtml(m,x)}${m.court?' · Campo '+esc(m.court):''}</p><p>${esc(m.tournamentName||'')}</p>${m.result?`<p class="result${loss}${win}">Risultato: ${esc(m.result)}</p>`:''}</div>`}).join(''):'<div class="empty">Nessuna partita pubblicata.</div>'}</div></div>`;$('homeView').classList.remove('active');$('profileView').classList.add('active')}
function route(){const m=location.hash.match(/^#player\/(.+)$/);if(m&&state.data)renderProfile(decodeURIComponent(m[1]));else{$('profileView').classList.remove('active');$('homeView').classList.add('active');if(state.data)renderHome()}}
function wire(){$('prevAgenda').onclick=()=>{state.agenda=add(state.agenda,-1);renderAgenda()};$('nextAgenda').onclick=()=>{state.agenda=add(state.agenda,1);renderAgenda()};$('agendaToday').onclick=()=>{state.agenda=new Date();renderAgenda()};$('prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};$('todayBtn').onclick=()=>{state.month=new Date();renderCalendar()};$('toggleAll').onclick=()=>{state.selected.size?state.selected.clear():state.data.players.forEach(p=>state.selected.add(p.id));renderHome()};$('backHome').onclick=()=>location.hash='';addEventListener('hashchange',route)}
async function load(){try{const [players,tournaments,matches,agenda,results,opponents,entries,status,diagnostics]=await Promise.all([v3json('players.json'),v3json('tournaments.json'),v3json('matches.json'),v3json('agenda.json'),v3json('results.json'),v3json('opponents.json'),v3json('tournament_entries.json'),v3json('sync_status.json'),v3json('diagnostics.json').catch(()=>({overall:'yellow',items:[]}))]);state.data={players:players.players||[],tournaments:tournaments.tournaments||[],matches:matches.matches||[],agenda:mergeAgenda(agenda.agenda||[],matches.matches||[]),results:results.results||[],opponents:opponents.opponents||[],tournamentEntries:entries.tournamentEntries||[],diagnostics,generatedAt:status.generatedAt||players.generatedAt||new Date().toISOString()};if(!state.selected.size)state.data.players.forEach(p=>state.selected.add(p.id));$('syncStatus').textContent='Live v3 · '+new Intl.DateTimeFormat('it-IT',{hour:'2-digit',minute:'2-digit'}).format(new Date(state.data.generatedAt));route()}catch(e){$('syncStatus').textContent='V3 non pronta';$('dailyAgenda').innerHTML='<div class="empty">File v3 separati non ancora disponibili. Attendo build v3.</div>';console.error(e)}}
wire();load();setInterval(load,30000);
