const PRIMARY='https://raw.githubusercontent.com/png8nftp9y-alt/png8nftp9y-alt.github.io/main/dist/v3/data.json';
const FALLBACK='https://raw.githubusercontent.com/png8nftp9y-alt/png8nftp9y-alt.github.io/main/dist/data-preview.json';
let DATA=null,VIEW='agenda';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const today=new Date().toISOString().slice(0,10);
const circuit=x=>{const s=String(x.circuit||x.source||x.sourceId||x.sourceName||'').toLowerCase();return s.includes('tennis')?'tennis-europe':s.includes('itf')?'itf':'fitp'};
const color=c=>c==='fitp'?'blue':c==='tennis-europe'?'orange':'green';
const isIntl=c=>c==='tennis-europe'||c==='itf';
const id=parts=>parts.map(x=>String(x||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')).filter(Boolean).join('__');
const fmt=d=>d?new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(d+'T12:00:00')):'—';
function pill(c,label){return `<span class="pill ${c}">${esc(label|| (c==='tennis-europe'?'TE':String(c).toUpperCase()))}</span>`}
function isDouble(m){return String(m.draw||m.eventType||m.category||m.partner||'').toLowerCase().includes('doppio')||String(m.draw||m.eventType||m.category||m.partner||'').toLowerCase().includes('double')||String(m.partner||'').includes('/')}
function normalizePreview(raw){
 const players=(raw.players||[]).map(p=>({...p,type:p.type||'current',monitoring:{entries:true,ordersOfPlay:true,results:true}}));
 const tournaments=(raw.tournaments||[]).map(t=>{const c=circuit(t);return {id:t.id||id([c,t.competitionId||t.name,t.playerId]),playerId:t.playerId||'',playerName:t.playerName||'',circuit:c,circuitColor:color(c),competitionId:t.competitionId||'',name:t.name||'',location:t.location||'',startDate:t.startDate||'',endDate:t.endDate||'',url:t.url||'',status:t.status||'',monitoring:{needsOrderOfPlay:!!t.startDate&&(!t.endDate||t.endDate>=today),needsResultSync:!!t.startDate}}});
 const tournamentEntries=tournaments.map(t=>({id:id(['entry',t.playerId,t.circuit,t.competitionId||t.name]),playerId:t.playerId,playerName:t.playerName,tournamentId:t.id,circuit:t.circuit,competitionId:t.competitionId,tournamentName:t.name,startDate:t.startDate,endDate:t.endDate,status:t.status||'detected'}));
 const matches=(raw.matches||[]).map(m=>{const c=circuit(m);const mid=m.id||id([c,m.competitionId,m.playerId,m.tournamentName,m.date,m.time,m.opponent,m.result]);return {id:mid,playerId:m.playerId||'',playerName:m.playerName||'',circuit:c,circuitColor:color(c),competitionId:m.competitionId||'',tournamentName:m.tournamentName||'',date:m.date||'',time:m.time||'',court:m.court||'',draw:m.draw||m.eventType||m.category||'',round:m.round||'',matchType:isDouble(m)?'doubles':'singles',partner:m.partner||'',opponent:m.opponent||'',opponentRanking:m.opponentRanking||'',opponentClub:m.opponentClub||'',opponentNationality:m.opponentNationality||'',result:m.result||'',advances:m.advances,status:m.status||(!m.result?'scheduled':'completed'),orderOfPlay:{source:m.todayAgendaSource||m.source||m.sourceId||'',file:m.orderOfPlayFile||'',line:m.orderOfPlayLine||'',confidence:m.todayAgendaSource?.includes('manual')?'manual':(m.time?'timed':'derived')}}});
 const agenda=matches.filter(m=>m.date).map(m=>({id:id(['agenda',m.id,m.date,m.time,m.court]),matchId:m.id,playerId:m.playerId,playerName:m.playerName,circuit:m.circuit,circuitColor:m.circuitColor,date:m.date,time:m.time,court:m.court,tournamentName:m.tournamentName,competitionId:m.competitionId,matchType:m.matchType,partner:m.partner,opponent:m.opponent,status:m.result?'completed':(m.date<today?'result_due':'scheduled'),orderOfPlay:m.orderOfPlay,result:m.result,advances:m.advances}));
 const results=matches.filter(m=>m.result).map(m=>({id:id(['result',m.id]),matchId:m.id,playerId:m.playerId,playerName:m.playerName,circuit:m.circuit,date:m.date,tournamentName:m.tournamentName,round:m.round,opponent:m.opponent,result:m.result,advances:m.advances,status:m.advances===false?'loss':m.advances===true?'win':'completed'}));
 const opponents=[]; for(const m of matches){if(!m.opponent)continue; for(const name of String(m.opponent).split('/').map(x=>x.trim()).filter(Boolean)){opponents.push({id:id(['opp',m.circuit,name,m.competitionId,m.playerId]),matchId:m.id,playerId:m.playerId,playerName:m.playerName,circuit:m.circuit,tournamentName:m.tournamentName,competitionId:m.competitionId,opponentName:name,ranking:m.opponentRanking||'',club:m.circuit==='fitp'?(m.opponentClub||''):'',nationality:isIntl(m.circuit)?(m.opponentNationality||''):'',dataStatus:(m.circuit==='fitp'&&!m.opponentClub)||(isIntl(m.circuit)&&!m.opponentNationality)?'needs_backfill':'ok'})}}
 const syncStatus={version:'cw-v3-agenda-first',generatedAt:raw.generatedAt||new Date().toISOString(),principle:'players -> tournament entries -> monitored tournaments -> orders of play -> agenda -> results -> opponent metadata',checks:{players:players.length,tournamentEntries:tournamentEntries.length,tournaments:tournaments.length,agenda:agenda.length,matches:matches.length,results:results.length,opponents:opponents.length,opponentsNeedsBackfill:opponents.filter(o=>o.dataStatus!=='ok').length},source:raw.version?'dist/data-preview fallback':'dist/v3'};
 return {version:'cw-v3-agenda-first',generatedAt:raw.generatedAt||new Date().toISOString(),players,tournamentEntries,tournaments,agenda,matches,results,opponents,syncStatus};
}
async function fetchJson(url){const r=await fetch(url+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));return r.json()}
async function getData(){try{return await fetchJson(PRIMARY)}catch{return normalizePreview(await fetchJson(FALLBACK))}}
function renderAgenda(){const rows=[...(DATA.agenda||[])].sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.time||'99:99').localeCompare(String(b.time||'99:99')));return rows.length?rows.map(a=>`<div class="row"><div class="time">${esc(a.time||fmt(a.date))}</div><div><div class="title">${esc(a.playerName)} ${pill(a.circuit)} ${a.status==='result_due'?pill('loss','risultato da recuperare'):''}</div><div class="meta">${fmt(a.date)}${a.court?' · campo '+esc(a.court):''} · ${esc(a.tournamentName)}</div><div class="meta">${a.partner&&a.partner!==a.playerName?'con '+esc(a.partner)+' · ':''}vs ${esc(a.opponent||'da definire')} · ${esc(a.matchType)}</div>${a.result?`<div class="meta">Risultato: ${esc(a.result)}</div>`:''}</div><div class="pill ${a.result?(a.advances===false?'loss':'win'):a.circuit}">${esc(a.status)}</div></div>`).join(''):'<div class="empty">Nessuna voce agenda.</div>'}
function renderCalendar(){const rows=[...(DATA.tournaments||[])].sort((a,b)=>String(a.startDate||'9999').localeCompare(String(b.startDate||'9999')));const byMonth={};for(const t of rows){const k=(t.startDate||'senza-data').slice(0,7);(byMonth[k] ||= []).push(t)}return Object.entries(byMonth).map(([m,items])=>`<div class="card"><h2>${esc(m==='senza-d'?'Senza data':m)}</h2>${items.map(t=>`<div class="calendarItem ${t.circuit}"><div><b>${esc(t.name)}</b> ${pill(t.circuit)}<div class="meta">${esc(t.playerName)} · ${esc(t.location)} · ${fmt(t.startDate)} - ${fmt(t.endDate)}</div></div></div>`).join('')}</div>`).join('')||'<div class="empty">Calendario vuoto.</div>'}
function renderPlayers(){const players=DATA.players||[];return players.length?`<div class="playersGrid">${players.map(p=>{const ts=(DATA.tournaments||[]).filter(t=>t.playerId===p.id).length;const ag=(DATA.agenda||[]).filter(a=>a.playerId===p.id&&!a.result).length;const res=(DATA.results||[]).filter(r=>r.playerId===p.id).length;return `<div class="playerCard"><h2>${esc(p.name)}</h2><div class="meta">${esc(p.type||'current')} · ${p.ranking?'classifica '+esc(p.ranking):'classifica da completare'} · ${p.club||p.membershipCard?'tessera '+esc(p.membershipCard||''):'tesseramento da completare'}</div><div class="stats"><span>${ts} tornei</span><span>${ag} agenda</span><span>${res} risultati</span></div><div class="meta">Circuiti: ${esc((p.circuits||[]).join(', ')||'da configurare')}</div></div>`}).join('')}</div>`:'<div class="empty">Nessun giocatore.</div>'}
function renderTournaments(){const rows=DATA.tournaments||[];return rows.length?rows.map(t=>`<div class="row"><div class="time">${fmt(t.startDate)}</div><div><div class="title">${esc(t.name)} ${pill(t.circuit)}</div><div class="meta">${esc(t.playerName)} · ${esc(t.location)} · ${fmt(t.startDate)} - ${fmt(t.endDate)}</div><div class="meta">${esc(t.status||'')} · ordine di gioco: ${t.monitoring?.needsOrderOfPlay?'da monitorare':'non attivo'}</div></div><div class="pill ${t.circuit}">Torneo</div></div>`).join(''):'<div class="empty">Nessun torneo.</div>'}
function renderResults(){const rows=DATA.results||[];return rows.length?rows.map(r=>`<div class="row"><div class="time">${fmt(r.date)}</div><div><div class="title">${esc(r.playerName)} ${pill(r.circuit)} <span class="pill ${r.status==='loss'?'loss':'win'}">${esc(r.status)}</span></div><div class="meta">${esc(r.tournamentName)} · ${esc(r.round)}</div><div class="meta">vs ${esc(r.opponent)} · risultato ${esc(r.result)}</div></div><div></div></div>`).join(''):'<div class="empty">Nessun risultato.</div>'}
function renderOpponents(){const rows=DATA.opponents||[];return rows.length?rows.map(o=>`<div class="row"><div class="time">${pill(o.circuit)}</div><div><div class="title">${esc(o.opponentName)} <span class="pill ${o.dataStatus==='ok'?'win':'loss'}">${esc(o.dataStatus)}</span></div><div class="meta">vs ${esc(o.playerName)} · ${esc(o.tournamentName)}</div><div class="meta">Classifica: ${esc(o.ranking||'da completare')} ${o.circuit==='fitp'?'· Circolo: '+esc(o.club||'da completare'):'· Nazionalità: '+esc(o.nationality||'da completare')}</div></div><div></div></div>`).join(''):'<div class="empty">Nessun avversario.</div>'}
function renderSync(){const s=DATA.syncStatus;return `<div class="card"><h2>Stato v3</h2><p>${esc(s.principle)}</p><pre>${esc(JSON.stringify(s.checks,null,2))}</pre><p class="meta">Fonte: ${esc(s.source||'dist/v3')} · Generato: ${esc(DATA.generatedAt)}</p></div>`}
function render(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===VIEW));$('#content').innerHTML=VIEW==='agenda'?renderAgenda():VIEW==='calendar'?renderCalendar():VIEW==='players'?renderPlayers():VIEW==='tournaments'?renderTournaments():VIEW==='results'?renderResults():VIEW==='opponents'?renderOpponents():renderSync()}
async function load(){DATA=await getData();$('#status').textContent='Aggiornato '+new Intl.DateTimeFormat('it-IT',{hour:'2-digit',minute:'2-digit'}).format(new Date(DATA.generatedAt));render()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{VIEW=b.dataset.view;render()});load().catch(e=>{$('#status').textContent='Errore dati';console.error(e)});setInterval(load,30000);
