import fs from 'node:fs/promises';
const NOW=new Date().toISOString();
const FROM='2025-12-18';
const BASE='https://dp-myfit-test-function-v2.azurewebsites.net';
const TENNIS_DISCIPLINE='4332';
const ALLOWED_SOURCES=new Set(['1','3']); // 1 TORNEI FITP, 3 CAMPIONATI A SQUADRE
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
const card=v=>String(v||'').replace(/\D+/g,'');
async function readJson(p,f){try{return JSON.parse(await fs.readFile(p,'utf8'))}catch{return f}}
async function writeJson(p,v){await fs.mkdir(p.split('/').slice(0,-1).join('/'),{recursive:true});await fs.writeFile(p,JSON.stringify(v,null,2)+'\n')}
async function post(path,body){const r=await fetch(BASE+path,{method:'POST',headers:{'content-type':'application/json','user-agent':'Mozilla/5.0 CourtWatch-v3/1.0','origin':'https://www.fitp.it','referer':'https://www.fitp.it/Tornei/Ricerca-tornei'},body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw Error(r.status+' '+t.slice(0,160));return t?JSON.parse(t):null}
function it(d){return `${String(d.getUTCDate()).padStart(2,'0')}/${String(d.getUTCMonth()+1).padStart(2,'0')}/${d.getUTCFullYear()}`}
function iso(v){const s=String(v||'');let m=s.match(/^(20\d{2})-(\d{2})-(\d{2})/);if(m)return m[0];m=s.match(/(\d{1,2})\D(\d{1,2})\D(20\d{2})/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''}
function sourceOk(c){return String(c.id_disciplina||'')===TENNIS_DISCIPLINE&&ALLOWED_SOURCES.has(String(c.cod_fonte||''))}
function wrongCircuitOrForeign(name){const n=norm(name);if(/CAMPIONATI ITALIANI|QUALIFICAZIONE AI CAMPIONATI|CAMPIONATI REGIONALI/.test(n))return false;return /^TE\s|\bTENNIS EUROPE\b|\bTEJT\b|\bITF\b|CORETENNIS|\b(PESCARA|CREMA|SASSUOLO|AGNO|KOPER|CORREGGIO)\b/.test(n)}
function veteran(obj){const text=norm([obj.nome_torneo,obj.name,obj.Description,obj.cat_eta,obj.tipo_competizione,obj.category,obj.Category].filter(Boolean).join(' '));return /\b(VETERAN|VETERANI|SENIOR|OVER\s*30|OVER\s*35|OVER\s*40|OVER\s*45|OVER\s*50|OVER\s*55|OVER\s*60|OVER\s*65|OVER\s*70|O30|O35|O40|O45|O50|O55|O60|O65|O70|O75|O80)\b/.test(text)}
function collectParticipants(node,into=[]){if(!node||typeof node!=='object')return into;if(Array.isArray(node)){for(const x of node)collectParticipants(x,into);return into}const name=[node.Name,node.FirstName,node.Nome].filter(Boolean).join(' '), surname=[node.Surname,node.LastName,node.Cognome].filter(Boolean).join(' ');const full1=`${name} ${surname}`.trim(), full2=`${surname} ${name}`.trim();const membershipCard=card(node.MembershipCard||node.Tessera||node.CardNumber||node.NumeroTessera||node.FitpCardNumber);if(full1||full2||membershipCard)into.push({full1,full2,membershipCard,raw:node});for(const [k,v] of Object.entries(node)){if(/result|score|winner|loser|match/i.test(k))continue;collectParticipants(v,into)}return into}
const players=(await readJson('players.json',{players:[]})).players||[];
const fitpPlayers=players.filter(p=>(p.circuits||[]).some(c=>String(c).toUpperCase()==='FITP'));
const playersByCard=new Map(fitpPlayers.filter(p=>card(p.membershipCard)).map(p=>[card(p.membershipCard),p]));
function matchParticipant(q){if(q.membershipCard&&playersByCard.has(q.membershipCard))return {player:playersByCard.get(q.membershipCard),method:'membership_card'};const n1=norm(q.full1),n2=norm(q.full2);const p=fitpPlayers.find(x=>norm(x.name)===n1||norm(x.name)===n2||(x.aliases||[]).some(a=>norm(a)===n1||norm(a)===n2));return p?{player:p,method:'name_alias'}:null}
const start0=new Date(FROM+'T00:00:00Z'), limit=new Date(Date.now()+420*864e5);
const specs=[];for(let s=new Date(start0);s<=limit;s=new Date(s.getTime()+14*864e5)){const e=new Date(Math.min(limit.getTime(),s.getTime()+13*864e5));for(const fonte of ['1','3'])specs.push({start:s,end:e,fonte})}
const all=[],queries=[],errors=[],excluded=[];let si=0;
function payload(s,skip){return{guid:'',profilazione:'',freetext:'',id_regione:'',id_provincia:'',id_stato:'',id_disciplina:TENNIS_DISCIPLINE,sesso:'',data_inizio:it(s.start),data_fine:it(s.end),tipo_competizione:'',categoria_eta:'',id_classifica:'',classifica:'',massimale_montepremi:'',id_area_regionale:'',ambito:'',cod_fonte:s.fonte,id_fonte:s.fonte==='1'?'TORNEI FITP':'CAMPIONATI A SQUADRE',rowstoskip:skip,fetchrows:100,sortcolumn:'',sortorder:''}}
async function listWorker(){while(si<specs.length){const s=specs[si++];let skip=0,total=Infinity;while(skip<total&&skip<5000){try{const r=await post('/api/v3/tornei/puc/list',payload(s,skip));const rows=r?.competizioni||[];total=Number(r?.record||rows.length||0);const official=rows.filter(x=>x.guid&&x.guid!=='11111111-1111-1111-1111-111111111111');all.push(...official);queries.push({mode:'STRUCTURED_NO_KEYWORD',discipline:TENNIS_DISCIPLINE,source:s.fonte,start:it(s.start),end:it(s.end),skip,rows:rows.length,official:official.length,total});if(rows.length<100)break;skip+=100}catch(e){errors.push(`list structured ${s.fonte} ${it(s.start)}: ${e.message}`);break}}}}
await Promise.all(Array.from({length:10},listWorker));
const unique=[...new Map(all.map(c=>[String(c.guid).toUpperCase(),c])).values()];
const comps=[];for(const c of unique){let reason=!sourceOk(c)?'excluded_wrong_discipline_or_source':wrongCircuitOrForeign(c.nome_torneo||c.name||'')?'excluded_wrong_circuit_or_foreign':veteran(c)?'excluded_veteran_tournament':'';if(reason)excluded.push({competitionId:c.guid,tournamentName:c.nome_torneo||c.name||'',id_disciplina:c.id_disciplina,cod_fonte:c.cod_fonte,id_fonte:c.id_fonte,reason});else comps.push(c)}
const entries=[],audit=[];let ci=0;
async function detailWorker(){while(ci<comps.length){const c=comps[ci++];try{const d=await post('/api/v3/puc/competizione/dettaglio',{competitionUid:c.guid});if(veteran({...c,...d,Description:d?.Description})){excluded.push({competitionId:c.guid,tournamentName:d?.Description||c.nome_torneo||'',reason:'excluded_veteran_tournament'});continue}const hits=new Map();for(const draw of d?.Tournaments||[]){if(veteran({...draw,Description:draw.TournamentDescription||draw.Description}))continue;for(const q of collectParticipants(draw.Participants||[])){const m=matchParticipant(q);if(!m)continue;const raw=q.raw||{};const h=hits.get(m.player.id)||{player:m.player,draws:[],ranking:raw.Ranking||raw.Classifica||'',membershipCard:q.membershipCard||card(raw.MembershipCard||raw.Tessera)||card(m.player.membershipCard),confirmedBy:new Set(),matchMethods:new Set()};h.draws.push(draw.TournamentDescription||draw.Description||'Tabellone/lista P.U.C.');h.confirmedBy.add('official_entry_or_draw_list');h.matchMethods.add(m.method);hits.set(m.player.id,h)}}for(const h of hits.values()){const st=iso(d.From||c.data_inizio), en=iso(d.To||c.data_fine);if(en&&en<FROM)continue;const row={playerId:h.player.id,playerName:h.player.name,circuit:'fitp',competitionId:c.guid,tournamentName:d.Description||c.nome_torneo||'',location:[d.Municipality||c.citta,d.Province||c.provincia].filter(Boolean).join(' '),startDate:st,endDate:en,draws:[...new Set(h.draws)],entryStatus:'entry_confirmed_by_official_list_or_draw',confirmationSource:[...h.confirmedBy][0],matchMethod:[...h.matchMethods].includes('membership_card')?'membership_card':'name_alias',filtersApplied:['id_disciplina:4332 tennis','cod_fonte:1 tornei_fitp OR cod_fonte:3 campionati_a_squadre','exclude:veterans','no:freetext_keywords'],resultUsedForEntry:false,ranking:h.ranking,membershipCard:h.membershipCard,sourceUrl:'https://www.fitp.it/Tornei/Dettaglio-Competizione?competitionId='+encodeURIComponent(c.guid),source:'FITP P.U.C. structured official filters: discipline tennis, source Tornei FITP/Campionati a squadre; no keyword discovery; no veterans; no results; membership card primary match',lastSeen:NOW};entries.push(row);audit.push({...row,auditStatus:'included'})}}catch(e){errors.push(`detail ${c.guid}: ${e.message}`);audit.push({competitionId:c.guid,tournamentName:c.nome_torneo||'',auditStatus:'detail_error',error:e.message})}}}
await Promise.all(Array.from({length:12},detailWorker));
const byPlayer=entries.reduce((a,e)=>{a[e.playerId]=(a[e.playerId]||0)+1;return a},{}), byMatchMethod=entries.reduce((a,e)=>{a[e.matchMethod]=(a[e.matchMethod]||0)+1;return a},{}), excludedByReason=excluded.reduce((a,e)=>{a[e.reason]=(a[e.reason]||0)+1;return a},{});
const out={version:'cw-v3-agenda-first',generatedAt:NOW,status:'complete_structured_no_keyword_tennis_tornei_fitp_squadre_no_veterans_membership_primary',source:'ex novo FITP P.U.C. discovery: structured filters only: id_disciplina=4332 tennis; cod_fonte=1 Tornei FITP or 3 Campionati a squadre; no keyword search; no veterans; entries confirmed only by official entry/draw lists; membership card primary; results never used',coverageFrom:FROM,queries:queries.length,competitionsListed:unique.length,competitionsChecked:comps.length,excludedByReason,entriesFound:entries.length,byPlayer,byMatchMethod,entries,errors:errors.slice(0,200)};
await writeJson('dist/v3/source_fitp_entries.json',out);
await writeJson('dist/v3/source_fitp_entries_audit.json',{...out,entries:undefined,audit,excluded});
console.log(JSON.stringify({...out,entries:undefined},null,2));
