#!/usr/bin/env bash
set -euo pipefail
readonly DIR=history PREFIX=itf/database ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
readonly FILES=(itf_participant_cache.json.gz itf_players_database.json.gz itf_results_database.json.gz)
aws_r2(){ aws --endpoint-url "$ENDPOINT" "$@"; }
validate(){ for f in "${FILES[@]}";do gzip -t "$DIR/$f";done; }
restore(){ local w g;w="$(mktemp -d)";trap 'rm -rf "${w:-}"' EXIT;if ! aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/pointers/current.json" "$w/p.json" --only-show-errors 2>/dev/null;then echo 'R2 has no ITF database yet.';return;fi;g="$(jq -er .generation "$w/p.json")";for f in "${FILES[@]}";do aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$f" "$DIR/$f" --only-show-errors;done;validate;echo "Restored ITF database $g from R2."; }
publish(){ local w g current;w="$(mktemp -d)";trap 'rm -rf "${w:-}"' EXIT;validate;g="$(sha256sum "${FILES[@]/#/$DIR/}"|sha256sum|cut -d' ' -f1)";jq -n --arg generation "$g" --arg at "$(date -u +%FT%TZ)" '{schemaVersion:1,generation:$generation,createdAt:$at}' > "$w/new.json";for f in "${FILES[@]}";do aws_r2 s3 cp "$DIR/$f" "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$f" --only-show-errors;done;aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/pointers/backup-1.json" "$w/b1.json" --only-show-errors 2>/dev/null||true;aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/pointers/current.json" "$w/current.json" --only-show-errors 2>/dev/null||true;test ! -s "$w/b1.json"||aws_r2 s3 cp "$w/b1.json" "s3://${R2_BUCKET}/${PREFIX}/pointers/backup-2.json" --only-show-errors;test ! -s "$w/current.json"||aws_r2 s3 cp "$w/current.json" "s3://${R2_BUCKET}/${PREFIX}/pointers/backup-1.json" --only-show-errors;aws_r2 s3 cp "$w/new.json" "s3://${R2_BUCKET}/${PREFIX}/pointers/current.json" --only-show-errors;echo "Published ITF database $g to R2."; }
case "${1:-}" in restore)restore;;publish)publish;;*)exit 2;;esac
