import fs from 'node:fs/promises';
import crypto from 'node:crypto';

export const NOW = new Date().toISOString();
export const TODAY = new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const HISTORY_FROM = '2025-12-18';
export const PAST_DAYS = Number(process.env.ITF_PAST_DAYS || 240);
export const HORIZON_DAYS = Number(process.env.ITF_HORIZON_DAYS || 730);
export const FROM = process.env.ITF_COVERAGE_FROM || new Date(Date.parse(`${TODAY}T00:00:00Z`) - PAST_DAYS * 864e5).toISOString().slice(0,10);
export const BASE = 'https://www.itftennis.com';
export const API = `${BASE}/tennis/api/TournamentApi`;
export const REGIONS = {
  europe:['ALB','AND','ARM','AUT','AZE','BEL','BIH','BLR','BUL','CRO','CYP','CZE','DEN','ENG','ESP','EST','FIN','FRA','GBR','GEO','GER','GRE','HUN','IRL','ISL','ISR','ITA','KOS','LAT','LTU','LUX','MDA','MKD','MLT','MNE','MON','NED','NOR','POL','POR','ROU','RUS','SLO','SMR','SRB','SUI','SVK','SWE','TUR','UKR'],
  americas:['ARG','ARU','BAH','BAR','BER','BOL','BRA','CAN','CHI','COL','CRC','CUB','CUR','DOM','ECU','ESA','FGU','GUA','GUY','HAI','HON','JAM','MEX','NCA','PAN','PAR','PER','PUR','SUR','TTO','URU','USA','VEN'],
  asia_pacific:['AUS','BAN','BRN','CAM','CHN','FIJ','GUM','HKG','INA','IND','JPN','KAZ','KGZ','KOR','LAO','MAC','MAS','MDV','MGL','MYA','NEP','NZL','PAK','PHI','PNG','SIN','SRI','TGA','THA','TJK','TKM','TPE','UZB','VIE'],
  africa_middle_east:['ALG','ANG','BOT','BRN','BUR','CMR','CIV','COD','CGO','EGY','ETH','GAB','GHA','IRQ','IRI','JOR','KEN','KSA','KUW','LBA','LES','MAD','MAR','MRI','MOZ','NAM','NGR','OMA','QAT','RSA','RWA','SEN','SEY','SUD','TAN','TOG','TUN','UAE','UGA','ZAM','ZIM']
};

export async function readJson(file,fallback={}){try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return fallback}}
export async function writeJson(file,value){await fs.mkdir(file.split('/').slice(0,-1).join('/'),{recursive:true});await fs.writeFile(file,JSON.stringify(value,null,2)+'\n')}
export const clean=v=>String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim();
export const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
export const hash=v=>crypto.createHash('sha256').update(String(v)).digest().readUInt32BE(0);
export const iso=d=>d.toISOString().slice(0,10);
export const addDays=(d,n)=>new Date(d.getTime()+n*864e5);
export function tournamentParts(url){const m=String(url||'').match(/\/en\/tournament\/([^/?#]+)\/([^/?#]+)\/(\d{4})\/([^/?#]+)(?:\/|$)/i);return m?{slug:m[1],country:m[2].toUpperCase(),year:m[3],competitionId:m[4].toUpperCase()}:null}
export function tournamentBase(url){const p=tournamentParts(url);return p?`${BASE}/en/tournament/${p.slug}/${p.country.toLowerCase()}/${p.year}/${p.competitionId.toLowerCase()}/`:''}
export function abs(href,base=BASE){try{return new URL(String(href||'').replace(/&amp;/g,'&'),base).toString()}catch{return''}}
export function links(html,base){const out=[];let m;const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;while((m=re.exec(html)))out.push({url:abs(m[1],base),text:clean(m[2]),index:m.index});return out}
export function aliases(player){const values=[player.name,...(player.aliases||[])].map(norm).filter(x=>x.split(' ').length>1);for(const v of [...values])values.push(v.split(' ').reverse().join(' '));return [...new Set(values)]}
export function matchPlayer(text,players){const n=norm(text);return players.find(p=>aliases(p).some(a=>n.includes(a)))||null}
export function flatten(value,path=[],out=[]){if(Array.isArray(value)){value.forEach((v,i)=>flatten(v,[...path,String(i)],out));return out}if(value&&typeof value==='object'){out.push({path:path.join('.'),value});for(const [k,v] of Object.entries(value))flatten(v,[...path,k],out)}return out}
export function field(obj,names){for(const [k,v] of Object.entries(obj||{}))if(names.some(n=>norm(k)===norm(n))&&['string','number','boolean'].includes(typeof v))return v;return''}
export function personName(obj){return String(field(obj,['playerName','name','fullName','displayName','participantName','teamPlayerName'])||'').trim()}
export function countryFor(t){return String(t.hostNationCode||t.countryCode||tournamentParts(t.sourceUrl)?.country||'').toUpperCase()}
export function regionFor(country){for(const [region,codes] of Object.entries(REGIONS))if(codes.includes(String(country||'').toUpperCase()))return region;return'other'}
let lastRequestAt=0;
const ITF_COOKIE_JAR=new Map();let ITF_REFERER=BASE;
function cookiePairs(headers){const values=headers.getSetCookie?.()||[headers.get('set-cookie')||''];return values.flatMap(v=>String(v).split(/,(?=\s*[^;,]+=)/)).map(v=>v.split(';')[0].trim()).filter(Boolean)}
function collectCookies(headers){for(const pair of cookiePairs(headers)){const i=pair.indexOf('=');if(i>0)ITF_COOKIE_JAR.set(pair.slice(0,i),pair.slice(i+1))}}
function cookieHeader(){return[...ITF_COOKIE_JAR].map(([k,v])=>`${k}=${v}`).join('; ')}
export async function bootstrapTournamentSession(t){ITF_COOKIE_JAR.clear();ITF_REFERER=BASE;let url=String(t?.sourceUrl||tournamentBase(t?.sourceUrl)||'');if(!url)return;for(let hop=0;hop<6;hop++){const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(Number(process.env.ITF_REQUEST_TIMEOUT_MS||20000)),headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36','accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','accept-language':'en-GB,en;q=0.9,it;q=0.8','cache-control':'no-cache','pragma':'no-cache','cookie':cookieHeader()}});collectCookies(r.headers);await r.arrayBuffer();const location=r.headers.get('location')||'';if(r.status<300||r.status>=400||!location){ITF_REFERER=url;return}url=new URL(location,url).toString()}throw new Error('itf_session_redirect_limit')}
export async function request(url,attempt=0){try{const spacing=Number(process.env.ITF_REQUEST_DELAY_MS||450),wait=Math.max(0,spacing-(Date.now()-lastRequestAt));if(wait)await new Promise(x=>setTimeout(x,wait));lastRequestAt=Date.now();const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(Number(process.env.ITF_REQUEST_TIMEOUT_MS||20000)),headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36','accept':'application/json,text/plain,*/*','accept-language':'en-GB,en;q=0.9,it;q=0.8','cache-control':'no-cache','pragma':'no-cache','cookie':cookieHeader(),'referer':ITF_REFERER,'x-requested-with':'XMLHttpRequest'}});collectCookies(r.headers);const text=await r.text(),json=(()=>{try{return JSON.parse(text)}catch{return null}})(),contentType=String(r.headers.get('content-type')||''),incapsula=/Incapsula|_Incapsula_Resource|Additional security check is required|hCaptcha/i.test(text);if(!incapsula&&(r.status===429||r.status>=500||(/\/tennis\/api\//.test(url)&&r.ok&&!json))&&attempt<3){await new Promise(x=>setTimeout(x,1800*(attempt+1)+Math.random()*700));return request(url,attempt+1)}return{ok:r.ok,status:r.status,url:r.url||url,text,json,contentType,incapsula,responseKind:incapsula?'incapsula_challenge':json?'json':contentType.includes('html')?'html':'non_json'}}catch(e){if(attempt<2){await new Promise(x=>setTimeout(x,1800*(attempt+1)));return request(url,attempt+1)}throw e}}
export function entryKey(e){return`${e.playerId}|${e.competitionId}`}
export function playerFromApi(raw={}){const p=raw||{},given=String(p.givenName||'').trim(),family=String(p.familyName||'').trim();return{id:String(p.playerId||''),name:[given,family].filter(Boolean).join(' '),givenName:given,familyName:family,nationalityCode:String(p.nationalityCode||p.nationality||''),profileLink:String(p.profileLink||''),singlesRank:p.singlesRank??p.rank??null,doublesRank:p.doublesRank??null}}
export function eventCombinations(json){const out=[];function walk(v,ctx={}){if(Array.isArray(v)){for(const x of v)walk(x,ctx);return}if(!v||typeof v!=='object')return;const next={...ctx};for(const k of['tournamentId','tourType','circuitCode','weekNumber','playerTypeCode','matchTypeCode','eventClassificationCode','drawsheetStructureCode'])if(v[k]!==undefined&&v[k]!==null&&v[k]!=='')next[k]=v[k];if(v.dataName&&v.valueCode!==undefined)next[v.dataName]=v.valueCode;if(next.tournamentId&&next.playerTypeCode&&next.matchTypeCode&&next.eventClassificationCode&&next.drawsheetStructureCode)out.push(next);for(const x of Object.values(v))if(x&&typeof x==='object')walk(x,next)}walk(json);return[...new Map(out.map(x=>[[x.tournamentId,x.weekNumber||0,x.playerTypeCode,x.matchTypeCode,x.eventClassificationCode,x.drawsheetStructureCode].join('|'),x])).values()]}
export async function tournamentEvents(t){for(let attempt=0;attempt<3;attempt++){await bootstrapTournamentSession(t);const r=await request(`${API}/GetEventFilters?tournamentKey=${encodeURIComponent(t.competitionId.toLowerCase())}`);if(r.incapsula){if(attempt<2){await new Promise(x=>setTimeout(x,1200*(attempt+1)));continue}throw new Error('GetEventFilters_incapsula_challenge')}if(!r.ok||!r.json)throw new Error(`GetEventFilters_${r.status||r.responseKind||'non_json'}`);return eventCombinations(r.json).map(c=>({...c,sourceUrl:t.sourceUrl||t.drawsResultsUrl||''}))}throw new Error('GetEventFilters_session_exhausted')}
export async function drawsheet(c){const q=new URLSearchParams({tournamentId:String(c.tournamentId),tourType:String(c.tourType||'N'),weekNumber:String(c.weekNumber||0),playerTypeCode:String(c.playerTypeCode),matchTypeCode:String(c.matchTypeCode),eventClassificationCode:String(c.eventClassificationCode),drawsheetStructureCode:String(c.drawsheetStructureCode)});for(let attempt=0;attempt<3;attempt++){const r=await request(`${API}/GetDrawsheet?${q}`);if(r.incapsula){if(attempt<2&&c.sourceUrl){await bootstrapTournamentSession({sourceUrl:c.sourceUrl});await new Promise(x=>setTimeout(x,1200*(attempt+1)));continue}throw new Error('GetDrawsheet_incapsula_challenge')}if(!r.ok||!r.json)throw new Error(`GetDrawsheet_${r.status||r.responseKind||'non_json'}`);return r.json}throw new Error('GetDrawsheet_session_exhausted')}
