#!/usr/bin/env bash
set -euo pipefail
readonly DIR=history CACHE=tennis_europe_participant_cache.json.gz INDEX=tennis_europe_participant_index.json.gz PREFIX=tennis-europe/cache ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
aws_r2(){ aws --endpoint-url "$ENDPOINT" "$@"; }
validate(){ gzip -t "$DIR/$CACHE";gzip -t "$DIR/$INDEX"; }
pointer(){ aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/pointers/$1.json" "$2" --only-show-errors 2>/dev/null; }
restore(){ local w p g;w="$(mktemp -d)";trap 'rm -rf "${w:-}"' EXIT;p="$w/current.json";if ! pointer current "$p";then echo 'R2 has no Tennis Europe cache yet; initializing a new database.';return;fi;g="$(jq -er .generation "$p")";aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$CACHE" "$DIR/$CACHE" --only-show-errors;aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$INDEX" "$DIR/$INDEX" --only-show-errors;validate;test "$(sha256sum "$DIR/$CACHE"|cut -d' ' -f1)" = "$(jq -r .files.participantCache.sha256 "$p")";test "$(sha256sum "$DIR/$INDEX"|cut -d' ' -f1)" = "$(jq -r .files.participantIndex.sha256 "$p")";echo "Restored verified Tennis Europe generation $g from R2."; }
publish(){ local w cs is g current;w="$(mktemp -d)";trap 'rm -rf "${w:-}"' EXIT;validate;cs="$(sha256sum "$DIR/$CACHE"|cut -d' ' -f1)";is="$(sha256sum "$DIR/$INDEX"|cut -d' ' -f1)";g="$(printf '%s\n%s\n' "$cs" "$is"|sha256sum|cut -d' ' -f1)";jq -n --arg g "$g" --arg cs "$cs" --arg is "$is" --arg at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" '{schemaVersion:1,generation:$g,createdAt:$at,files:{participantCache:{name:"tennis_europe_participant_cache.json.gz",sha256:$cs},participantIndex:{name:"tennis_europe_participant_index.json.gz",sha256:$is}}}' > "$w/new.json";if pointer current "$w/current.json";then current="$(jq -r .generation "$w/current.json")";if test "$current" = "$g";then echo 'Tennis Europe cache unchanged; R2 not rewritten.';return;fi;fi;aws_r2 s3 cp "$DIR/$CACHE" "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$CACHE" --only-show-errors;aws_r2 s3 cp "$DIR/$INDEX" "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$INDEX" --only-show-errors;aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$CACHE" "$w/cache.gz" --only-show-errors;aws_r2 s3 cp "s3://${R2_BUCKET}/${PREFIX}/generations/$g/$INDEX" "$w/index.gz" --only-show-errors;test "$(sha256sum "$w/cache.gz"|cut -d' ' -f1)" = "$cs";test "$(sha256sum "$w/index.gz"|cut -d' ' -f1)" = "$is";pointer backup-1 "$w/b1.json"||true;test ! -s "$w/b1.json"||aws_r2 s3 cp "$w/b1.json" "s3://${R2_BUCKET}/${PREFIX}/pointers/backup-2.json" --only-show-errors;test ! -s "$w/current.json"||aws_r2 s3 cp "$w/current.json" "s3://${R2_BUCKET}/${PREFIX}/pointers/backup-1.json" --only-show-errors;aws_r2 s3 cp "$w/new.json" "s3://${R2_BUCKET}/${PREFIX}/pointers/current.json" --only-show-errors;echo "Published verified Tennis Europe generation $g to R2."; }
cleanup(){ local w;w="$(mktemp -d)";trap 'rm -rf "${w:-}"' EXIT;for slot in current backup-1 backup-2;do pointer "$slot" "$w/$slot.json"||true;done;aws_r2 s3api list-objects-v2 --bucket "$R2_BUCKET" --prefix "${PREFIX}/generations/" --output json|jq -r '.Contents[]?.Key'|cut -d/ -f4|sort -u > "$w/all";jq -r .generation "$w"/*.json 2>/dev/null|sort -u > "$w/keep";comm -23 "$w/all" "$w/keep"|while read -r generation;do test -z "$generation"||aws_r2 s3 rm "s3://${R2_BUCKET}/${PREFIX}/generations/$generation/" --recursive --only-show-errors;done; }
case "${1:-}" in restore)restore;;publish)publish;cleanup;;*)echo 'Usage: tennis-europe-r2-cache.sh restore|publish'>&2;exit 2;;esac
