import fs from 'node:fs/promises';
const base='../../dist/v3/universal',out='seed-universal.sql';
const read=async name=>JSON.parse(await fs.readFile(`${base}/${name}.json`,'utf8'));
const [manifest,players,tournaments,entries,schedules,matches,results]=await Promise.all(['manifest','players','tournaments','entries','schedules','matches','results'].map(read));
const esc=value=>`'${String(value??'').replaceAll("'","''")}'`,payload=row=>esc(JSON.stringify(row));
const sql=['PRAGMA foreign_keys=ON;','BEGIN TRANSACTION;','DELETE FROM results;','DELETE FROM matches;','DELETE FROM schedules;','DELETE FROM entries;','DELETE FROM tournaments;','DELETE FROM players;'];
for(const r of players.players||[])sql.push(`INSERT INTO players(id,courtwatch_id,display_name,active,payload) VALUES(${esc(r.id)},${esc(r.courtwatchId)},${esc(r.displayName)},${r.active===false?0:1},${payload(r)});`);
for(const r of tournaments.tournaments||[])sql.push(`INSERT INTO tournaments(id,circuit,source_tournament_id,start_date,end_date,payload) VALUES(${esc(r.id)},${esc(r.circuit)},${esc(r.sourceTournamentId)},${esc(r.startDate)},${esc(r.endDate)},${payload(r)});`);
for(const r of entries.entries||[])sql.push(`INSERT INTO entries(id,tournament_id,player_id,circuit,state,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.playerId)},${esc(r.circuit)},${esc(r.state)},${payload(r)});`);
for(const r of schedules.schedules||[])sql.push(`INSERT INTO schedules(id,tournament_id,match_id,circuit,local_date,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.matchId)},${esc(r.circuit)},${esc(r.localDate)},${payload(r)});`);
for(const r of matches.matches||[])sql.push(`INSERT INTO matches(id,tournament_id,circuit,played_date,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.circuit)},${esc(r.playedDate)},${payload(r)});`);
for(const r of results.results||[])sql.push(`INSERT INTO results(id,tournament_id,match_id,circuit,played_date,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.matchId)},${esc(r.circuit)},${esc(r.playedDate)},${payload(r)});`);
sql.push(`INSERT OR REPLACE INTO generations(id,generated_at,schema_version,status,counts_json) VALUES('current',${esc(manifest.generatedAt)},${esc(manifest.version)},'green',${esc(JSON.stringify(manifest.counts))});`,'COMMIT;');
await fs.writeFile(out,sql.join('\n')+'\n');console.log(JSON.stringify({output:out,counts:manifest.counts}));
