import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const base='../../dist/v3/universal',out='seed-universal';
const read=async file=>JSON.parse(await fs.readFile(file,'utf8'));
const [manifest,players,tournaments,entries,schedules,matches,results,legacy,mapDoc,playerConfig,observed]=await Promise.all([
  ...['manifest','players','tournaments','entries','schedules','matches','results'].map(name=>read(`${base}/${name}.json`)),
  read('../../data.json'),read('../../dist/v3/tournaments.json'),read('../../players.json'),process.env.D1_SKIP_OBSERVED==='1'?Promise.resolve({players:[]}):read('observed-players.json'),
]);
const esc=value=>`'${String(value??'').replaceAll("'","''")}'`,payload=row=>esc(JSON.stringify(row));
const circuit=row=>{const s=String(row.circuit||row.sourceId||row.sourceName||'').toLowerCase();return s.includes('tennis-europe')||s.includes('tennis europe')?'tennis-europe':s.includes('itf')?'itf':'fitp'};
const sql=['PRAGMA foreign_keys=ON;'],cleanup=[],different=columns=>columns.map(column=>`${column} IS NOT excluded.${column}`).join(' OR '),idList=rows=>rows.map(row=>esc(row.id)).join(',');
const deleteMissing=(table,rows,scope='1=1')=>cleanup.push(rows.length?`DELETE FROM ${table} WHERE ${scope} AND id NOT IN (${idList(rows)});`:`DELETE FROM ${table} WHERE ${scope};`);
for(const r of observed.players||[])sql.push(`INSERT INTO observed_players(source_key,circuit,official_id,normalized_name,display_name,monitored,observations,first_observed_at,last_observed_at,payload) VALUES(${esc(r.sourceKey)},${esc(r.circuit)},${esc(r.officialId)},${esc(r.normalizedName)},${esc(r.displayName)},${r.monitored?1:0},${Number(r.observations)||1},${esc(r.firstObservedAt)},${esc(r.lastObservedAt)},${payload(r)}) ON CONFLICT(source_key) DO UPDATE SET circuit=excluded.circuit,official_id=excluded.official_id,normalized_name=excluded.normalized_name,display_name=excluded.display_name,monitored=excluded.monitored,observations=excluded.observations,first_observed_at=excluded.first_observed_at,last_observed_at=excluded.last_observed_at,payload=excluded.payload WHERE ${different(['circuit','official_id','normalized_name','display_name','monitored','observations','first_observed_at','last_observed_at','payload'])};`);
const playerRows=players.players||[];deleteMissing('players',playerRows);for(const r of playerRows)sql.push(`INSERT INTO players(id,courtwatch_id,display_name,active,payload) VALUES(${esc(r.id)},${esc(r.courtwatchId)},${esc(r.displayName)},${r.active===false?0:1},${payload(r)}) ON CONFLICT(id) DO UPDATE SET courtwatch_id=excluded.courtwatch_id,display_name=excluded.display_name,active=excluded.active,payload=excluded.payload WHERE ${different(['courtwatch_id','display_name','active','payload'])};`);
const tournamentRows=tournaments.tournaments||[];deleteMissing('tournaments',tournamentRows,"id NOT LIKE 'te-oop:%'");for(const r of tournamentRows)sql.push(`INSERT INTO tournaments(id,circuit,source_tournament_id,start_date,end_date,payload) VALUES(${esc(r.id)},${esc(r.circuit)},${esc(r.sourceTournamentId)},${esc(r.startDate)},${esc(r.endDate)},${payload(r)}) ON CONFLICT(id) DO UPDATE SET circuit=excluded.circuit,source_tournament_id=excluded.source_tournament_id,start_date=excluded.start_date,end_date=excluded.end_date,payload=excluded.payload WHERE ${different(['circuit','source_tournament_id','start_date','end_date','payload'])};`);
const entryRows=entries.entries||[];deleteMissing('entries',entryRows);for(const r of entryRows)sql.push(`INSERT INTO entries(id,tournament_id,player_id,circuit,state,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.playerId)},${esc(r.circuit)},${esc(r.state)},${payload(r)}) ON CONFLICT(id) DO UPDATE SET tournament_id=excluded.tournament_id,player_id=excluded.player_id,circuit=excluded.circuit,state=excluded.state,payload=excluded.payload WHERE ${different(['tournament_id','player_id','circuit','state','payload'])};`);
const scheduleRows=(schedules.schedules||[]).filter(r=>r.circuit!=='tennis-europe');deleteMissing('schedules',scheduleRows,"circuit!='tennis-europe'");for(const r of scheduleRows)sql.push(`INSERT INTO schedules(id,tournament_id,match_id,circuit,local_date,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.matchId)},${esc(r.circuit)},${esc(r.localDate)},${payload(r)}) ON CONFLICT(id) DO UPDATE SET tournament_id=excluded.tournament_id,match_id=excluded.match_id,circuit=excluded.circuit,local_date=excluded.local_date,payload=excluded.payload WHERE ${different(['tournament_id','match_id','circuit','local_date','payload'])};`);
const matchRows=(matches.matches||[]).filter(r=>r.circuit!=='tennis-europe');deleteMissing('matches',matchRows,"circuit!='tennis-europe'");for(const r of matchRows)sql.push(`INSERT INTO matches(id,tournament_id,circuit,played_date,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.circuit)},${esc(r.playedDate)},${payload(r)}) ON CONFLICT(id) DO UPDATE SET tournament_id=excluded.tournament_id,circuit=excluded.circuit,played_date=excluded.played_date,payload=excluded.payload WHERE ${different(['tournament_id','circuit','played_date','payload'])};`);
const resultRows=(results.results||[]).filter(r=>r.circuit!=='tennis-europe');deleteMissing('results',resultRows,"circuit!='tennis-europe'");for(const r of resultRows)sql.push(`INSERT INTO results(id,tournament_id,match_id,circuit,played_date,payload) VALUES(${esc(r.id)},${esc(r.tournamentId)},${esc(r.matchId)},${esc(r.circuit)},${esc(r.playedDate)},${payload(r)}) ON CONFLICT(id) DO UPDATE SET tournament_id=excluded.tournament_id,match_id=excluded.match_id,circuit=excluded.circuit,played_date=excluded.played_date,payload=excluded.payload WHERE ${different(['tournament_id','match_id','circuit','played_date','payload'])};`);
const configPlayers=[...new Map((playerConfig.players||[]).map(p=>[p.id,p])).values()],allowed=new Set(configPlayers.map(p=>p.id)),legacyById=new Map((legacy.players||[]).map(p=>[p.id,p]));
const appPlayers=configPlayers.map(p=>({...(legacyById.get(p.id)||{}),...p}));
const appTournaments=(mapDoc.tournaments||[]).filter(row=>allowed.has(row.playerId));
const appMatches=[];
cleanup.push(`DELETE FROM app_players WHERE seq>${appPlayers.length};`,`DELETE FROM app_tournaments WHERE seq>${appTournaments.length};`,"DELETE FROM app_matches WHERE COALESCE(json_extract(payload,'$.circuit'),'')!='tennis-europe';");
appPlayers.forEach((r,i)=>sql.push(`INSERT INTO app_players(seq,id,payload) VALUES(${i+1},${esc(r.id)},${payload(r)}) ON CONFLICT(seq) DO UPDATE SET id=excluded.id,payload=excluded.payload WHERE ${different(['id','payload'])};`));
appTournaments.forEach((r,i)=>sql.push(`INSERT INTO app_tournaments(seq,player_id,competition_id,circuit,payload) VALUES(${i+1},${esc(r.playerId)},${esc(r.competitionId)},${esc(circuit(r))},${payload(r)}) ON CONFLICT(seq) DO UPDATE SET player_id=excluded.player_id,competition_id=excluded.competition_id,circuit=excluded.circuit,payload=excluded.payload WHERE ${different(['player_id','competition_id','circuit','payload'])};`));
appMatches.forEach((r,i)=>sql.push(`INSERT INTO app_matches(seq,player_id,competition_id,match_date,payload) VALUES(${i+1},${esc(r.playerId)},${esc(r.competitionId)},${esc(r.date)},${payload(r)}) ON CONFLICT(seq) DO UPDATE SET player_id=excluded.player_id,competition_id=excluded.competition_id,match_date=excluded.match_date,payload=excluded.payload WHERE ${different(['player_id','competition_id','match_date','payload'])};`));
// Child rows are removed before parents; every DELETE only targets records no
// longer present in the generated projection.
sql.splice(1,0,...cleanup.reverse());
const counts={...manifest.counts,observedPlayers:(observed.players||[]).length,observedByCircuit:observed.counts||{},observedSources:observed.sources||{},appPlayers:appPlayers.length,appTournaments:appTournaments.length,appMatches:appMatches.length};
if(process.env.D1_SKIP_OBSERVED==='1'){delete counts.observedPlayers;delete counts.observedByCircuit;delete counts.observedSources;}
// Stable fingerprint of the effective application payload. generatedAt is
// intentionally excluded so unchanged scheduled runs do not rewrite D1.
const hashPayload={players:players.players||[],tournaments:tournaments.tournaments||[],entries:entries.entries||[],schedules:(schedules.schedules||[]).filter(r=>r.circuit!=='tennis-europe'),matches:(matches.matches||[]).filter(r=>r.circuit!=='tennis-europe'),results:(results.results||[]).filter(r=>r.circuit!=='tennis-europe'),appPlayers,appTournaments,observed:process.env.D1_SKIP_OBSERVED==='1'?[]:(observed.players||[])};
const volatileHashKeys=new Set(['generatedAt','lastSeen','lastSeenAt','lastDrawCheckedAt','acceptanceLastUpdated']);
const canonicalHashValue=value=>Array.isArray(value)?value.map(canonicalHashValue):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([key])=>!volatileHashKeys.has(key)).map(([key,item])=>[key,canonicalHashValue(item)])):value;
counts.importHash=crypto.createHash('sha256').update(JSON.stringify(canonicalHashValue(hashPayload))).digest('hex');
sql.push(`INSERT OR REPLACE INTO generations(id,generated_at,schema_version,status,counts_json) VALUES('current',${esc(manifest.generatedAt)},${esc(manifest.version)},'green',json_patch(COALESCE((SELECT counts_json FROM generations WHERE id='current'),'{}'),${esc(JSON.stringify(counts))}));`);
await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});
await fs.writeFile(`${out}/import-hash.txt`,counts.importHash+'\n');
// Keep remote D1 imports comfortably below the storage-operation timeout.
// The files remain ordered and idempotent, so a transient failure retries only
// the current 500-statement block instead of rebuilding the whole generation.
const statements=sql.filter(x=>x!=='PRAGMA foreign_keys=ON;'),chunkSize=500;
const control=statements.filter(x=>x.startsWith('DELETE FROM ')),data=statements.filter(x=>!x.startsWith('DELETE FROM '));
for(let index=0;index<control.length;index++)await fs.writeFile(`${out}/${String(index).padStart(3,'0')}-control.sql`,['PRAGMA foreign_keys=ON;',control[index]].join('\n')+'\n');
for(let start=0,index=control.length;start<data.length;start+=chunkSize,index++){const chunk=['PRAGMA foreign_keys=ON;',...data.slice(start,start+chunkSize)];await fs.writeFile(`${out}/${String(index).padStart(3,'0')}-data.sql`,chunk.join('\n')+'\n')}
console.log(JSON.stringify({output:out,files:control.length+Math.ceil(data.length/chunkSize),controlStatements:control.length,dataStatements:data.length,counts}));
