const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS','Access-Control-Allow-Headers':'Content-Type'};
const json=(value,status=200)=>Response.json(value,{status,headers:{...cors,'Cache-Control':'public, max-age=30'}});
const parseRows=result=>(result?.results||[]).map(row=>JSON.parse(row.payload));
async function all(env,table,where='',binds=[]){return parseRows(await env.DB.prepare(`SELECT payload FROM ${table} ${where}`).bind(...binds).all())}
function adminAuthorized(request,env){if(!env.ADMIN_TOKEN)return false;const value=request.headers.get('authorization')||'';if(!value.startsWith('Basic '))return false;try{const decoded=atob(value.slice(6)),i=decoded.indexOf(':');return i>=0&&decoded.slice(i+1)===env.ADMIN_TOKEN}catch{return false}}
const adminHeaders={'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Frame-Options':'DENY','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function adminPage(env){const generation=await env.DB.prepare("SELECT * FROM generations WHERE id='current'").first();const tables=['players','tournaments','entries','schedules','app_players','app_tournaments','app_matches'];const counts={};for(const table of tables)counts[table]=(await env.DB.prepare(`SELECT COUNT(*) AS n FROM ${table}`).first())?.n??0;const rows=Object.entries(counts).map(([name,count])=>`<tr><td>${esc(name)}</td><td>${esc(count)}</td></tr>`).join('');return `<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Court Watch Admin</title><style>body{font:16px system-ui;background:#07111f;color:#e8eef7;margin:0}main{max-width:920px;margin:auto;padding:28px}h1{margin:0 0 8px}.card{background:#111f31;border:1px solid #29415d;border-radius:14px;padding:18px;margin:18px 0}table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #29415d;text-align:left}.ok{color:#62d99b}.muted{color:#9fb0c5}</style><main><h1>Court Watch Admin v1</h1><p class="muted">Sola lettura · protezione server-side</p><section class="card"><h2>Generazione D1</h2><p class="ok">Stato: ${esc(generation?.status||'non inizializzato')}</p><p>Generata: ${esc(generation?.generated_at||'—')}</p><p>Schema: ${esc(generation?.schema_version||'—')}</p></section><section class="card"><h2>Conteggi</h2><table><thead><tr><th>Tabella</th><th>Record</th></tr></thead><tbody>${rows}</tbody></table></section><section class="card"><h2>Copertura v1</h2><p>D1 e proiezione applicativa disponibili. Diagnostica FITP, Tennis Europe, ITF, watchdog, R2 e workflow verranno collegate nella prossima estensione protetta.</p></section></main></html>`}
function appSnapshot(players,tournaments,entries,schedules,manifest){
  const playerMap=new Map(players.map(p=>[p.id,p])),tournamentMap=new Map(tournaments.map(t=>[t.id,t]));
  const appPlayers=players.filter(p=>p.active!==false).map(p=>({id:p.courtwatchId,name:p.displayName,club:p.club||'',membershipCard:p.identifiers?.fitpMembershipCard||'',circuits:p.circuits||[]}));
  const appTournaments=entries.flatMap(e=>{const p=playerMap.get(e.playerId),t=tournamentMap.get(e.tournamentId);return p&&t?[{playerId:p.courtwatchId,playerName:p.displayName,competitionId:t.sourceTournamentId,name:t.name,location:t.location||'',startDate:t.startDate,endDate:t.endDate,officialStartDate:t.officialStartDate,status:e.state,entryStatus:e.state,entryPosition:e.acceptance?.position??null,calendarListLabel:e.acceptance?.label||'',sourceId:t.circuit,sourceName:t.circuit,circuit:t.circuit,sourceUrl:t.source?.url||''}]:[]});
  const appMatches=schedules.flatMap(s=>{const t=tournamentMap.get(s.tournamentId);return(s.playerIds||[]).map(id=>{const p=playerMap.get(id);return p&&t?{id:s.id,playerId:p.courtwatchId,playerName:p.displayName,competitionId:t.sourceTournamentId,tournamentName:t.name,date:s.localDate,time:s.localTime||'',court:s.court||'',status:s.status,opponent:s.opponentText||'',partner:s.partnerText||'',sourceId:t.circuit}:null}).filter(Boolean)});
  return{generatedAt:manifest.generated_at||new Date().toISOString(),schemaVersion:manifest.schema_version,players:appPlayers,tournaments:appTournaments,matches:appMatches};
}
export default{
  async fetch(request,env){
    try{
      if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});
      if(request.method!=='GET')return json({error:'method_not_allowed'},405);
      const url=new URL(request.url),path=url.pathname.replace(/\/$/,'');
      if(path==='/admin'){if(!env.ADMIN_TOKEN)return new Response('Admin non configurata',{status:503,headers:adminHeaders});if(!adminAuthorized(request,env))return new Response('Autenticazione richiesta',{status:401,headers:{...adminHeaders,'WWW-Authenticate':'Basic realm="Court Watch Admin", charset="UTF-8"'}});return new Response(await adminPage(env),{headers:adminHeaders})}
      if(path===''||path==='/health'){const row=await env.DB.prepare("SELECT * FROM generations WHERE id='current'").first();return json({service:'courtwatch-app-api',status:row?.status||'uninitialized',generation:row||null})}
      if(path==='/v1/manifest'){const row=await env.DB.prepare("SELECT * FROM generations WHERE id='current'").first();return json(row||{},row?200:503)}
      if(path==='/v1/players')return json({players:await all(env,'players','WHERE active=1 ORDER BY display_name')});
      if(path==='/v1/tournaments'){const circuit=url.searchParams.get('circuit');return json({tournaments:await all(env,'tournaments',circuit?'WHERE circuit=? ORDER BY start_date':'',circuit?[circuit]:[])})}
      if(path==='/v1/entries'){const playerId=url.searchParams.get('playerId');return json({entries:await all(env,'entries',playerId?'WHERE player_id=?':'',playerId?[playerId]:[])})}
      if(path==='/v1/app-snapshot'){const[players,tournaments,matches,manifest]=await Promise.all([all(env,'app_players','ORDER BY seq'),all(env,'app_tournaments','ORDER BY seq'),all(env,'app_matches','ORDER BY seq'),env.DB.prepare("SELECT * FROM generations WHERE id='current'").first()]);return json({generatedAt:manifest?.generated_at||new Date().toISOString(),schemaVersion:manifest?.schema_version||'',players,tournaments,matches})}
      return json({error:'not_found'},404);
    }catch(error){console.error(error);return json({error:'internal_error'},500)}
  },
};
